// client/amane/ui/game/Announcement.svelte
<script lang="ts">
  // A highlighted announcement row: a coloured translucent panel with a bold
  // description and a body. Used for deaths, anonymous announcements, etc. — the
  // caller picks the colour and copy per event type. Like Message, this is pure
  // presentation; the parent resolves whatever text goes in.
  //
  // `color` is any CSS colour string (hex, rgb, named). The translucency is applied
  // here — a low-opacity tint over the base plus a solid accent bar — so callers
  // just hand in a solid colour and don't have to think about opacity or Tailwind's
  // class purging (dynamic colours can't be Tailwind classes).
  interface Props {
    color: string;
    description: string;
    content: string;
  }
  let { color, description, content }: Props = $props();
</script>

<div class="px-4 py-1">
  <div
    class="relative overflow-hidden rounded-md border-l-2 px-3 py-2"
    style="border-color: {color}"
  >
    <!-- tint layer: the colour at low opacity over the base background -->
    <div
      class="pointer-events-none absolute inset-0"
      style="background-color: {color}; opacity: 0.12"
    ></div>

    <div class="relative">
      <div
        class="text-xs font-semibold uppercase tracking-wide"
        style="color: {color}"
      >
        {description}
      </div>
      <div class="mt-0.5 whitespace-pre-wrap break-words text-sm text-neutral-200">
        {content}
      </div>
    </div>
  </div>
</div>

// amane/amane-ui/game/channels/Announcement.tsx
// The shared card every non-message event renders as. Pure presentation; the caller resolves the
// text and picks the colour per event type.
//
// `color` is any CSS colour string (a `var(--color-event-*)` reference). The translucency is
// applied here so callers hand in a solid colour without worrying about it.
import type { ReactNode } from "react";
import { TimeStamp } from "../Name.tsx";

export function Announcement({
  color,
  description,
  content,
  children,
  timestamp,
}: {
  color: string;
  description: string;
  // Plain text is the common case. Pass `children` instead when the body needs markup — an
  // embedded ping chip, say.
  content?: string;
  children?: ReactNode;
  timestamp?: number;
}) {
  return (
    <div className="px-3 py-0.5">
      <div className="relative overflow-hidden border-l-2 px-2.5 py-1.5" style={{ borderColor: color }}>
        <div className="pointer-events-none absolute inset-0" style={{ backgroundColor: color, opacity: 0.12 }} />
        <div className="relative">
          <div className="flex items-baseline justify-between gap-2">
            <div className="text-sm font-semibold uppercase tracking-wide" style={{ color }}>
              {description}
            </div>
            {timestamp !== undefined && <TimeStamp timestamp={timestamp} />}
          </div>
          <div className={`mt-0.5 break-words text-sm text-ink ${children ? "" : "whitespace-pre-wrap"}`}>
            {children ?? content}
          </div>
        </div>
      </div>
    </div>
  );
}
