// amane/amane-core/ui/game/Announcement.svelte
<script lang="ts">
  // Pure presentation; the parent resolves the text and picks the colour per event type.
  //
  // `color` is any CSS colour string. The translucency is applied here so callers hand in a solid
  // colour and don't have to think about Tailwind's class purging — dynamic colours cannot be
  // Tailwind classes.
  import type { Snippet } from "svelte";
  import type { GameView } from "../../game/view.svelte";
  import TimeStamp from "./TimeStamp.svelte";

  interface Props {
    color: string;
    description: string;
    // Plain text is the common case. Pass `children` instead when the body needs markup — an
    // embedded ping chip, say — and it renders in the same styled slot.
    content?: string;
    children?: Snippet;
    // The game time the announcement appeared, shown in the header (with real wall time on hover).
    timestamp?: number;
    view?: GameView;
  }
  let { color, description, content, children, timestamp, view }: Props = $props();
</script>

<div class="px-3 py-0.5">
  <div
    class="relative overflow-hidden border-l-2 px-2.5 py-1.5"
    style="border-color: {color}"
  >
    <div
      class="pointer-events-none absolute inset-0"
      style="background-color: {color}; opacity: 0.12"
    ></div>

    <div class="relative">
      <div class="flex items-baseline justify-between gap-2">
        <div
          class="text-[0.8rem] font-semibold uppercase tracking-wide"
          style="color: {color}"
        >
          {description}
        </div>
        {#if timestamp !== undefined}
          <TimeStamp {timestamp} {view} />
        {/if}
      </div>
      <!-- pre-wrap only for the plain-text case, where the copy carries its own newlines. Markup
           children lay out with their own elements, so collapsing source whitespace is what's wanted. -->
      <div
        class="mt-0.5 break-words text-sm text-neutral-200 {children
          ? ''
          : 'whitespace-pre-wrap'}"
      >
        {#if children}{@render children()}{:else}{content}{/if}
      </div>
    </div>
  </div>
</div>

// amane/amane-ui/game/channels/Announcement.tsx
// The shared card every non-message event renders as. Pure presentation; the caller resolves the
// text and picks the colour per event type.
//
// `color` is any CSS colour string (a `var(--color-event-*)` reference). The translucency is
// applied here so callers hand in a solid colour without worrying about it.
import type { ReactNode } from "react";
import { TimeStamp } from "../Name.tsx";

export function Announcement({
  color,
  description,
  content,
  children,
  timestamp,
}: {
  color: string;
  description: string;
  // Plain text is the common case. Pass `children` instead when the body needs markup — an
  // embedded ping chip, say.
  content?: string;
  children?: ReactNode;
  timestamp?: number;
}) {
  return (
    <div className="px-3 py-0.5">
      <div className="relative overflow-hidden border-l-2 px-2.5 py-1.5" style={{ borderColor: color }}>
        <div className="pointer-events-none absolute inset-0" style={{ backgroundColor: color, opacity: 0.12 }} />
        <div className="relative">
          <div className="flex items-baseline justify-between gap-2">
            <div className="text-sm font-semibold uppercase tracking-wide" style={{ color }}>
              {description}
            </div>
            {timestamp !== undefined && <TimeStamp timestamp={timestamp} />}
          </div>
          <div className={`mt-0.5 break-words text-sm text-ink ${children ? "" : "whitespace-pre-wrap"}`}>
            {children ?? content}
          </div>
        </div>
      </div>
    </div>
  );
}
