// client/amane/ui/game/ChannelView.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import Input from "../kit/Input.svelte";
  import {
    actorLabel,
    GAME_STATE_KEY,
    displayKey,
    phaseAnnouncement,
    playerLabel,
  } from "../../game_state.svelte.ts";
  import { CLIENT_KEY, type ClientState } from "../../client.svelte.ts";
  import { UI_STATE_KEY } from "../../ui_state.svelte.ts";
  import { now } from "../../time.svelte.ts";
  import type { GameEvent, GameState, WriteEvent } from "../../game_state.svelte.ts";
  import type { UiState } from "../../ui_state.svelte.ts";
  import type { ActionRequest, ActorDisplay, PollSubject, ProsecutionPhaseView } from "../../bindings";
  import { slotKeyFromString, slotKeyToString } from "../../bindings";
  import { viewerToActor } from "../../types";
  import { formatDuration } from "../../lib/utils";
  import Button from "../kit/Button.svelte";
  import Message from "./Message.svelte";
  import Announcement from "./Announcement.svelte";
  import NotebookWrite from "./NotebookWrite.svelte";
  import NotebookPass from "./NotebookPass.svelte";

  const game = getContext<GameState>(GAME_STATE_KEY);

  const client = getContext<ClientState>(CLIENT_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);

  let message_content = $state("");
  let channel_name = $derived(get_channel_name());
  let scroller = $state<HTMLElement>();

  // Admin implicitly has every permission; players go by their channel_perms entry
  // (which may be absent, meaning no access).
  const is_admin = $derived(ui.viewer === "Admin");

  // News is its own selection, not a channel — it always exists on the frontend and
  // carries no channel data. Its backing channel (for messages and perms) is
  // news_channel_id, which may be absent; that's only a lookup, never news's identity.
  // Every other channel is keyed directly by selected_channel. World events render
  // regardless (see the events derived) since they live per-view, not on the channel.
  const is_news = $derived(ui.is_news);
  const backing_channel_id = $derived(
    is_news ? game.news_channel_id : ui.selected_channel,
  );

  const current_channel = $derived(
    backing_channel_id
      ? game.resolve_channel(ui.viewer, backing_channel_id)
      : undefined,
  );
  const current_perms = $derived(
    backing_channel_id
      ? game.views.get(ui.viewer)?.channel_views.get(backing_channel_id)?.perms
      : undefined,
  );
  // Info channels are frontend-only, read-only feeds (name reveals, autopsies): you
  // can never send in one, and their owner can always read them (no engine perms).
  const is_info = $derived(current_channel?.kind === "Info");
  // Bug feeds are read-only surveillance logs: never interactable, and always readable to
  // whoever the feed was listed for (visibility is gated when it's shown in the sidebar).
  const is_bug = $derived(current_channel?.kind === "Bug");
  const archived = $derived(current_channel?.archived ?? false);
  // You can only send in a channel that actually exists. For news with no backing
  // channel this is false, so it isn't interactable — only the event log shows.
  // Archived channels are read-only for everyone, admin included.
  const can_send = $derived(
    current_channel != null &&
      !archived &&
      !is_info &&
      !is_bug &&
      (is_admin || (current_perms?.send ?? false)),
  );
  const can_read = $derived(is_info || is_bug || is_admin || (current_perms?.read ?? false));
  // This viewer has left the channel's viewport, so nothing further about it will arrive: what is
  // shown is the last thing they heard, not the current state. Distinct from `archived`, which
  // means the channel itself is over for everyone — this one is personal, and the channel may well
  // still be busy without them. Admin reads every viewport, so it is never frozen for them.
  const frozen = $derived(
    !is_admin &&
      !is_info &&
      backing_channel_id != null &&
      (game.views
        .get(ui.viewer)
        ?.frozen(
          is_bug
            ? undefined // bug feeds are gated by visible_bugs, which never shrinks
            : game.channel_viewport(backing_channel_id),
        ) ??
        false),
  );
  // Notebook-ness isn't a channel kind — it's derived from the channel->notebook mapping.
  // A non-undefined notebook_id both identifies the channel as a notebook and gives the
  // Write affordance its target.
  const notebook_id = $derived(
    backing_channel_id
      ? game.notebook_for_channel(backing_channel_id)
      : undefined,
  );
  // Loggability is a global channel property (SetChannelLoggable). Show it, and let a viewer
  // with loggability control flip it. Synthetic info/bug feeds aren't engine channels, so the
  // control never applies there.
  const loggable = $derived(
    backing_channel_id ? game.is_channel_loggable(backing_channel_id) : false,
  );
  // Show the status on any real engine channel (info/bug feeds aren't engine channels);
  // it becomes an interactive toggle only for viewers with loggability control.
  const show_loggability = $derived(current_channel != null && !is_info && !is_bug);
  const can_control_loggability = $derived(
    show_loggability && (is_admin || (current_perms?.loggability_control ?? false)),
  );
  // Whether this notebook is currently on loan (global notebook property). Shown as a badge.
  const notebook_borrowed = $derived(
    notebook_id ? game.is_notebook_borrowed(slotKeyToString(notebook_id)) : false,
  );
  let write_open = $state(false);
  let pass_open = $state(false);

  // The displays the viewer may send as in the current channel (their "send as"
  // options, delivered by UpdateChannelView). Empty for admin (always sends as System).
  const available_displays = $derived(
    backing_channel_id
      ? (game.views.get(ui.viewer)?.channel_views.get(backing_channel_id)
          ?.displays ?? [])
      : [],
  );
  let selected_display_key = $state<string | null>(null);

  // Keep the selection valid as the channel (and thus the options) changes: if the
  // current pick isn't available, fall back to the first option.
  $effect(() => {
    const keys = available_displays.map(displayKey);
    if (!selected_display_key || !keys.includes(selected_display_key)) {
      selected_display_key = keys[0] ?? null;
    }
  });

  // Admin reads the System view's world events; players read their own.
  // TODO: engine must emit world events to System for this to be populated.
  const current_view = $derived(
    is_admin ? game.system_view() : game.views.get(ui.viewer),
  );
  // News may be selected without a backing channel object, so fall back to a name.
  const header_name = $derived(channel_name ?? (is_news ? "News" : ""));

  function get_channel_name(): string | null {
    return backing_channel_id
      ? (game.resolve_channel(ui.viewer, backing_channel_id)?.name ?? null)
      : null;
  }

  function player_name(id: string): string {
    return playerLabel(id, game.players);
  }

  // Short label for a poll notice rendered in-channel (the Polls panel is where you vote).
  function poll_notice_text(subject: PollSubject): string {
    if ("Generic" in subject) return subject.Generic;
    if ("CivilianArrest" in subject) {
      return `Arrest ${playerLabel(slotKeyToString(subject.CivilianArrest), game.players)}`;
    }
    const beh = subject.OrgAbility as Record<string, unknown>;
    const name = Object.keys(beh)[0] ?? "";
    return name.replace(/([a-z])([A-Z])/g, "$1 $2");
  }

  function sender_display(): ActorDisplay {
    if (ui.viewer === "Admin") return "System";
    const chosen = available_displays.find(
      (d) => displayKey(d) === selected_display_key,
    );
    return chosen ?? { Raw: slotKeyFromString(ui.viewer) };
  }

  function display_string(display: ActorDisplay): string {
    return actorLabel(display, game.players);
  }

  // Discord-style chunking: a message is a "continuation" (its sender header is dropped)
  // when the immediately preceding rendered event is ALSO a message, from the same display,
  // within this window. Any non-message event in between breaks the chain — the run must be
  // uninterrupted. Each message stays its own row (own hover, own timestamp); only the header
  // is suppressed.
  const GROUP_WINDOW_MS = 45_000;
  function is_grouped_message(
    prev: GameEvent | undefined,
    curr: GameEvent,
  ): boolean {
    if (!prev || !("Message" in prev.data) || !("Message" in curr.data)) return false;
    if (
      displayKey(prev.data.Message.sender_display) !==
      displayKey(curr.data.Message.sender_display)
    )
      return false;
    return curr.timestamp - prev.timestamp <= GROUP_WINDOW_MS;
  }

  // A notebook write, rendered with everything a viewer holding the book needs: who wrote,
  // the name written, the outcome (lethal / target saved / no match), any death note, and
  // the writer's remaining successes/attempts. success=true means the name matched a real
  // player; target_saved means the kill didn't land (write immunity, or an earlier pending
  // death on that target was cancelled by this write).
  function write_event_text(w: WriteEvent): string {
    const lines = [`${player_name(w.user_id)} wrote the name "${w.true_name}".`];
    if (!w.success) {
      lines.push("Outcome: the name matched no one — no effect.");
    } else if (w.target_saved) {
      lines.push(
        "Outcome: valid name, but the target was saved (write immunity, or a pending death was cancelled).",
      );
    } else if (w.delay > 0) {
      lines.push(`Outcome: lethal — the target dies in ${formatDuration(w.delay)}.`);
    } else {
      lines.push("Outcome: lethal — the target dies immediately.");
    }
    if (w.message) lines.push(`Note: ${w.message}`);
    lines.push(
      `Successes left: ${w.successes_remaining} · Attempts left: ${w.attempts_remaining}`,
    );
    return lines.join("\n");
  }

  // Colour by outcome: red = lethal, amber = valid-but-saved, grey = no match.
  function write_event_color(w: WriteEvent): string {
    if (!w.success) return "#6b7280";
    if (w.target_saved) return "#f59e0b";
    return "#ef4444";
  }

  // News-feed text for a prosecution start/advance/end (derived from the phase diff).
  function prosecution_event_text(pe: {
    prosecutor_display: ActorDisplay;
    defendant_display: ActorDisplay;
    phase: ProsecutionPhaseView;
    ended: boolean;
  }): string {
    return phaseAnnouncement(
      pe.phase,
      display_string(pe.prosecutor_display),
      display_string(pe.defendant_display),
      pe.ended,
    );
  }

  async function send_message() {
    // backing_channel_id resolves news to its real channel key; can_send already
    // gates the box on the channel existing, so this is null only defensively.
    if (!backing_channel_id || !message_content.trim()) return;
    const request: ActionRequest = {
      actor: viewerToActor(ui.viewer),
      timestamp: now(),
      payload: {
        SendMessage: {
          channel_id: slotKeyFromString(backing_channel_id),
          display: sender_display(),
          content: message_content.trim(),
        },
      },
    };
    await client.dispatch(request);
    message_content = "";
    console.log("message sent");
  }

  async function toggle_loggable() {
    if (!backing_channel_id) return;
    await client.dispatch({
      actor: viewerToActor(ui.viewer),
      timestamp: now(),
      payload: {
        SetLoggable: {
          channel_id: slotKeyFromString(backing_channel_id),
          loggable: !loggable,
        },
      },
    });
  }

  // based on the context, choose which events to include, push them into a unified list, and then sort the list
  const events: GameEvent[] = $derived.by(() => {
    // Nothing selected → nothing to show. News (which has no channel key) still
    // counts as selected, so gate on the selection itself, not the channel key.
    if (!ui.selected) {
      return [];
    }

    let accum: GameEvent[] = [];

    // News always shows the viewer's world events (deaths, anonymous
    // announcements). These are game events, not channel messages, so they render
    // regardless of whether the news channel currently exists or the viewer has
    // any perms for it.
    if (is_news && current_view) {
      accum = accum.concat(current_view.events);
    }

    // Channel messages/writes follow the normal perm rules. The channel object may
    // be absent — a channel removed while still selected, or news that doesn't
    // currently exist — in which case there are simply no messages to add.
    const channel = current_channel;
    if (channel) {
      // Full history if admin or currently readable; if the viewer was once a real
      // member (had_positive) but read is now off, only messages up to the cutoff;
      // otherwise (never a member, e.g. L & Watari) → nothing.
      if (can_read) {
        accum = accum.concat(channel.events);
      } else if (current_perms && current_perms.had_positive) {
        accum = accum.concat(
          channel.events.filter(
            (val) => val.timestamp <= current_perms.read_updated,
          ),
        );
      }
    }

    // oldest to newest
    accum.sort((a, b) => a.timestamp - b.timestamp);

    return accum;
  });

  // Switching channels always lands at the bottom. The <main> element is reused
  // across channels, so its scrollTop would otherwise carry over from the last one.
  $effect(() => {
    ui.selected; // track: re-run when the selected channel/news changes
    scroller?.scrollTo({ top: scroller.scrollHeight });
  });

  // New messages in the current channel stick to the bottom, but only if the user
  // is already near it (so scrolling up to read history isn't yanked back down).
  // Runs after the DOM flush, so scrollHeight already includes the new content.
  $effect(() => {
    events.length; // track: re-run whenever the event list grows
    if (!scroller) return;
    const near_bottom =
      scroller.scrollHeight - scroller.scrollTop - scroller.clientHeight < 100;
    if (near_bottom) scroller.scrollTo({ top: scroller.scrollHeight });
  });
</script>

<div class="h-full w-full bg-neutral-900 text-neutral-100">
  {#if ui.selected}
    <div class="grid h-full w-full grid-rows-[auto_1fr_auto]">
      <header
        class="flex h-12 shrink-0 items-center gap-2 border-b border-neutral-800 px-4 shadow-sm"
      >
        <span class="text-lg font-medium text-neutral-500">#</span>
        <span class="font-semibold text-neutral-100">{header_name}</span>
        {#if archived}
          <span
            class="ml-1 rounded bg-neutral-800 px-1.5 py-0.5 text-xs text-neutral-400"
          >
            archived
          </span>
        {/if}

        <!-- Right-aligned status badges: notebook borrow status, then loggability (a toggle
             for viewers with loggability control, otherwise a read-only badge). -->
        <div class="ml-auto flex items-center gap-2">
          {#if notebook_borrowed}
            <span
              class="rounded bg-sky-600/20 px-2 py-0.5 text-xs font-medium text-sky-300"
              title="This notebook is currently on loan (being borrowed)."
            >
              Borrowed
            </span>
          {/if}

          {#if show_loggability}
            {@const cls = loggable
              ? "bg-amber-600/20 text-amber-400"
              : "bg-neutral-800 text-neutral-500"}
            {#if can_control_loggability}
              <button
                class="rounded px-2 py-0.5 text-xs font-medium hover:brightness-125 {cls}"
                title="Toggle whether messages sent here can be logged (autopsied / relayed to bugs)"
                onclick={toggle_loggable}
              >
                Logging {loggable ? "on" : "off"}
              </button>
            {:else}
              <span
                class="rounded px-2 py-0.5 text-xs font-medium {cls}"
                title="Whether messages sent here can be logged (autopsied / relayed to bugs)"
              >
                Logging {loggable ? "on" : "off"}
              </span>
            {/if}
          {/if}
        </div>
      </header>

      <main bind:this={scroller} class="min-h-0 overflow-y-auto py-4">
        {#each events as event, i (event)}
          {#if "Message" in event.data}
            <Message
              sender={display_string(event.data.Message.sender_display)}
              content={event.data.Message.content}
              timestamp={event.timestamp}
              grouped={is_grouped_message(events[i - 1], event)}
            />
          {:else if "Write" in event.data}
            {@const w = event.data.Write}
            <Announcement
              color={write_event_color(w)}
              description="Notebook Write"
              content={write_event_text(w)}
            />
          {:else if "Death" in event.data}
            {@const d = event.data.Death}
            <Announcement
              color="#ef4444"
              description="Death"
              content={`${player_name(d.target_id)} has died.\nReal name: ${d.true_name}\nRole: ${d.role}${d.death_message ? `\n\n${d.death_message}` : ""}`}
            />
          {:else if "AnonymousAnnouncement" in event.data}
            <Announcement
              color="#a855f7"
              description="Anonymous Announcement"
              content={event.data.AnonymousAnnouncement.content}
            />
          {:else if "RevealTrueName" in event.data}
            {@const r = event.data.RevealTrueName}
            <Announcement
              color="#3b82f6"
              description="Name Reveal"
              content={`${player_name(r.target_id)}'s true name is ${r.true_name}.`}
            />
          {:else if "RevealNotebookHolding" in event.data}
            {@const r = event.data.RevealNotebookHolding}
            <Announcement
              color="#3b82f6"
              description="Notebook Check"
              content={`${player_name(r.target_id)} is ${r.holding ? "" : "not "}currently holding a notebook.`}
            />
          {:else if "Bugged" in event.data}
            {@const b = event.data.Bugged}
            <Announcement
              color="#eab308"
              description="Surveillance"
              content={b.context === "Custody"
                ? "You are bugged: your messages are being monitored while you are in custody."
                : "You have been bugged. Your messages are being monitored."}
            />
          {:else if "RoleUpdate" in event.data}
            <Announcement
              color="#8b5cf6"
              description="Role"
              content={`Your role is now ${event.data.RoleUpdate.role}.`}
            />
          {:else if "TrueNameUpdate" in event.data}
            <Announcement
              color="#8b5cf6"
              description="True Name"
              content={`Your true name is now ${event.data.TrueNameUpdate.true_name}.`}
            />
          {:else if "NotebookReceived" in event.data}
            <Announcement
              color="#ef4444"
              description="Notebook"
              content="A notebook has come into your possession."
            />
          {:else if "PollNotice" in event.data}
            {@const pn = event.data.PollNotice}
            <Announcement
              color="#6366f1"
              description={pn.outcome ? `Vote ${pn.outcome}` : "Vote started"}
              content={pn.opener
                ? `${poll_notice_text(pn.subject)}\nStarted by ${game.actor_name(pn.opener)}`
                : poll_notice_text(pn.subject)}
            />
          {:else if "PseudocideRevival" in event.data}
            {@const r = event.data.PseudocideRevival}
            <Announcement
              color="#10b981"
              description="Revival"
              content={`${player_name(r.target_id)} is alive.`}
            />
          {:else if "KidnapReveal" in event.data}
            {@const kr = event.data.KidnapReveal}
            {@const victim = kr.victim ? player_name(kr.victim) : "the victim"}
            <Announcement
              color="#f59e0b"
              description="Kidnap Reveal"
              content={kr.kidnapper
                ? `Authorities have recovered ${victim}, and ${player_name(kr.kidnapper)} was revealed as the kidnapper.`
                : `Authorities have recovered ${victim}, but the kidnapper stayed anonymous.`}
            />
          {:else if "Kidnapping" in event.data}
            {@const k = event.data.Kidnapping}
            <Announcement
              color="#f59e0b"
              description="Kidnapping"
              content={`${player_name(k.target_id)} has been kidnapped.`}
            />
          {:else if "ProsecutionEvent" in event.data}
            {@const pe = event.data.ProsecutionEvent}
            <Announcement
              color="#e11d48"
              description={pe.ended ? "Prosecution Ended" : "Prosecution"}
              content={prosecution_event_text(pe)}
            />
          {/if}
        {/each}

        {#if is_news}
          {#if !can_read}
            <!-- news always renders world events (announcements) above; only the
                 chat messages are gated. Spell out the events-vs-messages split. -->
            <div class="px-4 py-3 text-center text-xs text-neutral-500">
              You don't have access to this channel. Announcements above are game
              events and are always shown here — but you can't see chat messages.
            </div>
          {/if}
        {:else if !can_read}
          {#if current_perms?.had_positive}
            <!-- was once a real member but read is now off: show history up to
                 the cutoff, no new messages. -->
            <div class="px-4 py-3 text-center text-xs text-neutral-500">
              You do not have read access to this channel. You will not receive
              new messages — only those up to your access cutoff are shown.
            </div>
          {:else}
            <!-- never a member: no perms entry, or an entry that was never
                 positive (e.g. L & Watari). -->
            <div class="px-4 py-3 text-center text-xs text-neutral-500">
              You don't have access to this channel.
            </div>
          {/if}
        {/if}
        {#if archived}
          <div class="px-4 py-3 text-center text-xs text-neutral-500">
            This channel has been archived.
          </div>
        {/if}
      </main>

      <footer class="shrink-0 px-4 pb-6 pt-1">
        <div class="flex items-center gap-2">
          {#if can_send && available_displays.length > 1}
            <!-- "send as" picker: only shown when the viewer has more than one display -->
            <select
              bind:value={selected_display_key}
              class="rounded-lg bg-neutral-800 px-2 py-2 text-sm text-neutral-200"
            >
              {#each available_displays as d (displayKey(d))}
                <option value={displayKey(d)}>{display_string(d)}</option>
              {/each}
            </select>
          {/if}

          <div class="flex-1">
            {#if can_send}
              <form
                onsubmit={async (event) => {
                  event.preventDefault();
                  await send_message();
                }}
              >
                <div
                  class="flex items-center gap-2 rounded-lg bg-neutral-800 px-2 py-1"
                >
                  <Input
                    bind:value={message_content}
                    placeholder={`Message #${channel_name ?? ""}`}
                    class="flex-1 border-0 bg-transparent shadow-none focus-visible:ring-0 dark:bg-transparent"
                  />
                  <Button
                    size="sm"
                    onclick={async () => {
                      await send_message();
                    }}>Send</Button
                  >
                </div>
              </form>
            {:else if is_bug}
              <div
                class="rounded-lg bg-neutral-800/50 px-4 py-2.5 text-center text-sm italic text-neutral-500"
              >
                {archived
                  ? "This surveillance feed is no longer active."
                  : "Read-only surveillance feed."}
              </div>
            {:else if archived}
              <div
                class="rounded-lg bg-neutral-800/50 px-4 py-2.5 text-center text-sm italic text-neutral-500"
              >
                This channel is archived and read-only.
              </div>
            {:else if frozen}
              <!-- Personal, unlike `archived`: the channel may still be busy, this viewer just
                   isn't in it any more. Say what they are looking at is old rather than let it
                   pass for current. -->
              <div
                class="rounded-lg bg-neutral-800/50 px-4 py-2.5 text-center text-sm italic text-neutral-500"
              >
                You are no longer in this channel. Everything above is what you last saw.
              </div>
            {:else}
              <div
                class="rounded-lg bg-neutral-800/50 px-4 py-2.5 text-center text-sm italic text-neutral-500"
              >
                You do not have permission to send messages in this channel.
              </div>
            {/if}
          </div>

          {#if notebook_id}
            <Button size="sm" variant="ghost" onclick={() => (pass_open = true)}>Pass</Button>
            <Button size="sm" variant="danger" onclick={() => (write_open = true)}>Write</Button>
          {/if}
        </div>
      </footer>

      {#if notebook_id}
        <NotebookWrite bind:open={write_open} notebookId={notebook_id} />
        <NotebookPass bind:open={pass_open} notebookId={notebook_id} />
      {/if}
    </div>
  {:else}
    <div class="flex h-full items-center justify-center text-neutral-500">
      Select a channel
    </div>
  {/if}
</div>

// amane/amane-ui/game/channels/ChannelView.tsx
// The main column: header, optional top-panel strip, the virtualized event list, and the composer.
// News is a selection with no backing channel of its own — world events render regardless of
// whether the News channel is held, since they live on the view rather than on the channel.
import type { ChannelProfileView } from "amane-client/bindings.ts";
import { slotKeyFromString, slotKeyToString } from "amane-client/bindings.ts";
import type { GameEvent, Outgoing } from "amane-client/game/types.ts";
import type { View } from "amane-client/game/view.ts";
import { PERM_SEND, ownPerms } from "amane-client/game/perms.ts";
import { feedEvents } from "amane-client/queries/feed.ts";
import { viewActor } from "amane-client/queries/session.ts";
import type { Session } from "amane-client/session.ts";
import { channelLabel, displayKey, execErrorText, mentionsViewer, refFromDisplay, refLabel } from "amane-client/text.ts";
import { useEffect, useRef, useState } from "react";
import type { VirtuosoHandle } from "react-virtuoso";
import { Virtuoso } from "react-virtuoso";
import { useNow, useSession } from "../../hooks.ts";
import { Button } from "../../kit/Button.tsx";
import { Select } from "../../kit/Input.tsx";
import { tint } from "../../style.ts";
import { useGameUi, useView } from "../game_ui.ts";
import { MentionInput } from "../mentions/MentionInput.tsx";
import { EventAnnouncement } from "./EventAnnouncement.tsx";
import { Message } from "./Message.tsx";
import { NotebookPass } from "./NotebookPass.tsx";
import { NotebookWrite } from "./NotebookWrite.tsx";
// Another agent's widget strip: polls / prosecutions. No props.
import { TopPanel } from "../side/TopPanel.tsx";

// Discord-style chunking: only the sender header is dropped, and any non-message event in between
// breaks the chain — the run must be uninterrupted.
const GROUP_WINDOW_MS = 45_000;
function isGroupedMessage(prev: GameEvent | undefined, curr: GameEvent): boolean {
  if (!prev || !("Message" in prev.data) || !("Message" in curr.data)) return false;
  if (displayKey(prev.data.Message.sender_display) !== displayKey(curr.data.Message.sender_display)) return false;
  return curr.timestamp - prev.timestamp <= GROUP_WINDOW_MS;
}

// A row of the list: something the view was told, or one of its own unconfirmed sends.
type Row = { event: GameEvent; outgoing?: Outgoing };

// Sends an outbox entry, or resends a refused one. Outlives the component: a send settles even
// after the channel is switched away from, so it works on the view and session it was handed.
async function deliver(session: Session, view: View, entry: Outgoing) {
  entry.error = null;
  if (!view.outbox.includes(entry)) view.outbox.push(entry);
  session.changed();
  const reply = await session.submit_action({
    actor: viewActor(view.own_key),
    timestamp: Date.now(),
    payload: {
      SendMessage: { channel_id: slotKeyFromString(entry.channel_id), profile_id: entry.profile_id, content: entry.content },
    },
  });
  if (reply.ok) view.outbox = view.outbox.filter((e) => e !== entry);
  else entry.error = reply.error;
  session.changed();
}

export function ChannelView() {
  const session = useSession();
  const ui = useGameUi();
  const view = useView();
  // News may hold death beats stamped in the future; this keeps the feed moving as the clock
  // reaches them even with nothing new delivered.
  useNow(250);

  const [message_content, setMessageContent] = useState("");
  const [selected_profile_key, setSelectedProfileKey] = useState<string | null>(null);
  const [write_open, setWriteOpen] = useState(false);
  const [pass_open, setPassOpen] = useState(false);
  const virtuoso = useRef<VirtuosoHandle>(null);

  // System holds no channel perms of its own — it reads every viewport without being a member of
  // anything — so it is the one thing a view cannot answer for itself, and sending is the one
  // affordance that still asks who is looking.
  const is_admin = ui.viewer === "System";
  const is_news = ui.selected?.kind === "news";
  const backing_channel_id = is_news ? view.news_channel : ui.selected?.kind === "channel" ? ui.selected.id : null;
  const current_channel = backing_channel_id ? view.channels.get(backing_channel_id) : undefined;
  // What this view may do here at all, folded over every name it holds. The composer asks the
  // chosen name instead; this is only "is there a send box".
  const current_perms = backing_channel_id ? ownPerms(view.channel_views.get(backing_channel_id)?.own ?? []) : undefined;

  const is_bug = current_channel?.kind === "Bug";
  const is_contact_log = current_channel?.kind === "ContactLog";
  const is_log = current_channel?.kind === "Log";
  const is_log_autopsy = is_log && backing_channel_id?.startsWith("autopsy:") === true;
  // A feed rather than a room: no perms, no send box, no loggability control.
  const read_only_feed = current_channel != null && current_channel.kind !== "Standard";
  const archived = current_channel?.archived ?? false;
  const can_send = current_channel != null && !archived && !read_only_feed && (is_admin || (current_perms?.send ?? false));
  // Holding the channel is what grants the history. A view that has lost read still holds what it
  // was given, and `frozen` below is what says so.
  const can_read = current_channel != null;
  // This viewer left the channel's viewport, so what is shown is the last thing they heard.
  const frozen = backing_channel_id != null && view.frozen(view.channels.get(backing_channel_id)?.viewport ?? null);
  // News is not a channel, so it goes stale on its own terms.
  const news_frozen = is_news && view.frozen(view.world_events_viewport);

  const link = backing_channel_id ? view.channels.get(backing_channel_id)?.link : null;
  const notebook_id = link && "notebook" in link ? link.notebook : undefined;
  const loggable = backing_channel_id ? (view.channels.get(backing_channel_id)?.loggable ?? false) : false;
  const show_loggability = current_channel != null && !read_only_feed;
  const can_control_loggability = show_loggability && (is_admin || (current_perms?.loggability_control ?? false));
  const notebook_borrowed = notebook_id ? (view.notebooks.get(notebook_id)?.borrowed ?? false) : false;
  const notebook_fake = notebook_id ? view.notebooks.get(notebook_id)?.fake : undefined;
  // The notebook's only physical home is this very channel, so archiving it IS destroying it.
  const notebook_destroyed = notebook_id !== undefined && archived;

  // The names this view may speak as here. Send belongs to the name rather than to the person, so
  // holding a name that cannot talk is not an option to offer. Empty for System, which holds no
  // name anywhere and speaks as nobody.
  const sendable_profiles = backing_channel_id
    ? (view.channel_views.get(backing_channel_id)?.own ?? []).filter((profile) => (profile.perms & PERM_SEND) !== 0)
    : [];
  const sendable_keys = sendable_profiles.map((p) => slotKeyToString(p.profile_id));
  // Falls back to the first option whenever the stored choice isn't (or is no longer) valid — no
  // effect needed, since this is just what "the current selection" derives to on every render.
  const effective_profile_key = selected_profile_key && sendable_keys.includes(selected_profile_key) ? selected_profile_key : (sendable_keys[0] ?? null);

  const channel_name = backing_channel_id ? (() => {
    const name = view.channels.get(backing_channel_id)?.name;
    return name != null ? channelLabel(name) : null;
  })() : null;
  const header_name = channel_name ?? (is_news ? "News" : "");

  const now = view.game_time_now();
  const events = ui.selected ? feedEvents(view, ui.selected, now) : [];

  // The messages this view sent here that the server hasn't confirmed, drawn after everything it
  // has, as rows shaped like the real thing so grouping treats them the same.
  const rows: Row[] = [
    ...events.map((event) => ({ event })),
    ...view.outbox
      .filter((entry) => entry.channel_id === backing_channel_id)
      .map((entry) => ({
        event: { timestamp: entry.timestamp, data: { Message: { content: entry.content, sender_display: entry.sender_display } } },
        outgoing: entry,
      })),
  ];

  function senderProfile(): ChannelProfileView | null {
    if (ui.viewer === "System") return null;
    return sendable_profiles.find((p) => slotKeyToString(p.profile_id) === effective_profile_key) ?? null;
  }

  // Shows at once, dim, and clears the box without waiting for the server.
  function sendMessage() {
    if (!backing_channel_id || !message_content.trim()) return;
    const profile = senderProfile();
    void deliver(session, view, {
      channel_id: backing_channel_id,
      profile_id: profile?.profile_id ?? null,
      sender_display: profile?.display ?? "System",
      content: message_content.trim(),
      timestamp: view.game_time_now(),
      error: null,
    });
    setMessageContent("");
  }

  function dismiss(entry: Outgoing) {
    view.outbox = view.outbox.filter((e) => e !== entry);
    session.changed();
  }

  async function toggleNotebookFake() {
    if (!notebook_id) return;
    await session.submit_action({
      actor: viewActor(ui.viewer),
      timestamp: Date.now(),
      payload: { SetNotebookFake: { notebook_id: slotKeyFromString(notebook_id), fake: !notebook_fake } },
    });
  }

  async function toggleLoggable() {
    if (!backing_channel_id) return;
    await session.submit_action({
      actor: viewActor(ui.viewer),
      timestamp: Date.now(),
      payload: { SetLoggable: { channel_id: slotKeyFromString(backing_channel_id), loggable: !loggable } },
    });
  }

  // A poll-panel jump lands here with the poll to reveal.
  useEffect(() => {
    if (!ui.jump_poll) return;
    const index = events.findIndex((e) => "PollNotice" in e.data && e.data.PollNotice.poll_id === ui.jump_poll);
    if (index >= 0) virtuoso.current?.scrollToIndex({ index, align: "center", behavior: "smooth" });
    ui.setJumpPoll(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ui.jump_poll]);

  return (
    <div className="flex h-full min-h-0 w-full flex-1 flex-col bg-surface text-ink">
      <header className="flex h-10 shrink-0 items-center gap-2 border-b border-edge px-3">
        <button
          type="button"
          className="flex h-8 w-8 shrink-0 items-center justify-center lg:hidden"
          title="Channels"
          onClick={() => ui.setDrawer("left")}
        >
          ☰
        </button>
        <span className="min-w-0 flex-1 truncate text-base font-semibold text-ink">{header_name}</span>

        {archived && <span className="shrink-0 border border-edge bg-panel px-1.5 py-0.5 text-xs text-ink-dim">archived</span>}

        <div className="ml-auto flex shrink-0 items-center gap-2">
          {notebook_destroyed && (
            <span className="border border-edge bg-panel px-2 py-0.5 text-xs font-medium text-ink-dim" title="This notebook no longer exists.">
              Destroyed
            </span>
          )}
          {notebook_borrowed && !notebook_destroyed && (
            <span className="px-2 py-0.5 text-xs font-medium" style={tint("var(--color-status-ipp)")} title="This notebook is currently on loan (being borrowed).">
              Borrowed
            </span>
          )}
          {notebook_fake !== undefined && !notebook_destroyed && (
            <NotebookFakeBadge fake={notebook_fake} editable={is_admin} onToggle={toggleNotebookFake} />
          )}
          {show_loggability && <LoggableBadge loggable={loggable} editable={can_control_loggability} onToggle={toggleLoggable} />}
        </div>

        <button
          type="button"
          className="flex h-8 w-8 shrink-0 items-center justify-center lg:hidden"
          title="People"
          onClick={() => ui.setDrawer("right")}
        >
          ⋯
        </button>
      </header>

      {ui.top_panel && <TopPanel />}

      {!ui.selected ? (
        <div className="flex flex-1 items-center justify-center text-ink-dim">Select a channel</div>
      ) : (
        <>
          <Virtuoso
            ref={virtuoso}
            className="min-h-0 flex-1"
            data={rows}
            followOutput="auto"
            computeItemKey={(index, row) => `${row.outgoing ? "out" : index}-${row.event.timestamp}`}
            itemContent={(index, { event, outgoing }) => {
              if ("Message" in event.data) {
                const msg = event.data.Message;
                const next = rows[index + 1]?.event;
                return (
                  <>
                    <Message
                      senderDisplay={msg.sender_display}
                      content={msg.content}
                      view={view}
                      timestamp={event.timestamp}
                      grouped={isGroupedMessage(rows[index - 1]?.event, event)}
                      last={!next || !isGroupedMessage(event, next)}
                      mentioned={mentionsViewer(view, msg.content)}
                      pending={outgoing !== undefined}
                    />
                    {outgoing?.error && (
                      <div className="flex flex-wrap items-center gap-2 px-4 pb-1.5 text-sm text-danger-text">
                        <span>Not sent: {execErrorText(outgoing.error)}</span>
                        <Button variant="ghost" size="sm" onClick={() => void deliver(session, view, outgoing)}>
                          Retry
                        </Button>
                        <Button variant="ghost" size="sm" onClick={() => dismiss(outgoing)}>
                          Dismiss
                        </Button>
                      </div>
                    )}
                  </>
                );
              }
              return <EventAnnouncement event={event} view={view} timestamp={event.timestamp} />;
            }}
            components={{
              Footer: () => (
                <div className="pb-2">
                  {is_news ? (
                    <>
                      {news_frozen && (
                        <p className="px-4 py-3 text-center text-sm" style={{ color: "var(--color-status-bugged)" }}>
                          You are no longer receiving news. Everything above is what you last heard.
                        </p>
                      )}
                      {!can_read && (
                        <p className="px-4 py-3 text-center text-sm text-ink-dim">
                          You don't have access to this channel. Announcements above are game events and are always shown here — but you can't see
                          chat messages.
                        </p>
                      )}
                    </>
                  ) : (
                    !can_read && (
                      <p className="px-4 py-3 text-center text-sm text-ink-dim">
                        You no longer have read access to this channel. Everything above is what you were given.
                      </p>
                    )
                  )}
                  {archived && <p className="px-4 py-3 text-center text-sm text-ink-dim">This channel has been archived.</p>}
                </div>
              ),
            }}
          />

          <footer className="shrink-0 px-3 pb-2 pt-1">
            <div className="flex items-end gap-2">
              {can_send && sendable_profiles.length > 1 && (
                <Select
                  value={effective_profile_key ?? ""}
                  onChange={(e) => setSelectedProfileKey(e.target.value)}
                  className="w-auto shrink-0"
                  options={sendable_profiles.map((p) => ({
                    value: slotKeyToString(p.profile_id),
                    label: refLabel(refFromDisplay(p.display, view.orgs), view.players),
                  }))}
                />
              )}

              <div className="min-w-0 flex-1">
                {can_send ? (
                  <div className="flex items-end gap-2">
                    <MentionInput value={message_content} onChange={setMessageContent} onSubmit={sendMessage} placeholder={`Message ${channel_name ?? ""}`} />
                    <Button size="sm" onClick={sendMessage}>
                      Send
                    </Button>
                  </div>
                ) : (
                  <ComposerNotice
                    text={
                      // Frozen outranks the read-only blurbs: "this is no longer live" is the more
                      // important of the two facts.
                      frozen && read_only_feed
                        ? "This feed no longer reaches you. Everything above is what it last relayed."
                        : is_bug
                          ? archived
                            ? "This surveillance feed is no longer active."
                            : "Read-only surveillance feed."
                          : is_contact_log
                            ? "Read-only contact log. Names here are how each contact appeared, not who was really behind it."
                            : is_log
                              ? `${is_log_autopsy ? "Autopsy — this actor's written record." : "Tap-in — what was written down on the tapped line."} Read-only.`
                              : archived
                                ? "This channel is archived and read-only."
                                : frozen
                                  ? "You are no longer in this channel. Everything above is what you last saw."
                                  : "You do not have permission to send messages in this channel."
                    }
                  />
                )}
              </div>

              {notebook_id && !notebook_destroyed && (
                <>
                  <Button size="sm" variant="ghost" onClick={() => setPassOpen(true)}>
                    Pass
                  </Button>
                  <Button size="sm" variant="danger" onClick={() => setWriteOpen(true)}>
                    Write
                  </Button>
                </>
              )}
            </div>
          </footer>

          {notebook_id && !notebook_destroyed && (
            <>
              <NotebookWrite open={write_open} onClose={() => setWriteOpen(false)} notebookId={slotKeyFromString(notebook_id)} />
              <NotebookPass open={pass_open} onClose={() => setPassOpen(false)} notebookId={slotKeyFromString(notebook_id)} />
            </>
          )}
        </>
      )}
    </div>
  );
}

function ComposerNotice({ text }: { text: string }) {
  return <p className="border border-edge bg-panel px-4 py-2.5 text-center text-sm italic text-ink-dim">{text}</p>;
}

function NotebookFakeBadge({ fake, editable, onToggle }: { fake: boolean; editable: boolean; onToggle: () => void }) {
  const color = fake ? "var(--color-status-kidnapped)" : "var(--color-event-revival)";
  const label = fake ? "Fake" : "Real";
  if (editable) {
    return (
      <button type="button" className="px-2 py-0.5 text-xs font-medium hover:brightness-125" style={tint(color)} title="Toggle whether this notebook is a decoy — a fake book's writes cannot kill." onClick={onToggle}>
        {label}
      </button>
    );
  }
  return (
    <span className="px-2 py-0.5 text-xs font-medium" style={tint(color)} title="A fake notebook's writes cannot kill. Only you and the host know this book's nature.">
      {label}
    </span>
  );
}

function LoggableBadge({ loggable, editable, onToggle }: { loggable: boolean; editable: boolean; onToggle: () => void }) {
  const style = loggable ? tint("var(--color-event-surveillance)") : undefined;
  const className = `px-2 py-0.5 text-xs font-medium ${loggable ? "" : "bg-panel text-ink-dim"}`;
  const label = `Logging ${loggable ? "on" : "off"}`;
  if (editable) {
    return (
      <button type="button" className={`${className} hover:brightness-125`} style={style} title="Toggle whether messages sent here can be logged (autopsied / relayed to bugs)" onClick={onToggle}>
        {label}
      </button>
    );
  }
  return (
    <span className={className} style={style} title="Whether messages sent here can be logged (autopsied / relayed to bugs)">
      {label}
    </span>
  );
}
