// amane/amane-core/ui/game/Message.svelte
<script lang="ts">
  // The sender resolves against the view — label via actorLabel, colour via displayColorVar, so the
  // header matches how that name renders everywhere else. Content still carries raw mention tokens,
  // which MentionText resolves against the same view.
  //
  // `grouped` only drops the sender header for a continuation of an uninterrupted run from the
  // same sender. Every row stays its own hover target and carries its own time.
  import { actorLabel, displayColorVar, statusBadgeStyle, statusLabels } from "../../game/helpers.svelte";
  import type { GameView } from "../../game/view.svelte";
  import type { ActorDisplay } from "../../bindings";
  import { slotKeyToString } from "../../bindings";
  import MentionText from "./MentionText.svelte";
  import Name from "./Name.svelte";
  import TimeStamp from "./TimeStamp.svelte";

  interface Props {
    senderDisplay: ActorDisplay;
    content: string;
    view: GameView;
    timestamp: number;
    grouped?: boolean;
    // Whether this message names the viewer. Tints the whole row and keeps the tint on hover,
    // rather than the ordinary hover highlight, so a ping stands out in a busy channel.
    mentioned?: boolean;
    // Last message of its chain — the next row is a different sender, a non-message, or nothing.
    // Only the tail of a chain carries the block's bottom spacing, so a header isn't shoved away
    // from its own continuation lines.
    last?: boolean;
  }
  let {
    senderDisplay,
    content,
    view,
    timestamp,
    grouped = false,
    mentioned = false,
    last = false,
  }: Props = $props();

  const senderLabel = $derived(actorLabel(senderDisplay, view.players));
  const senderColor = $derived(displayColorVar(senderDisplay, view));
  // A player sender routes through Name so its header is clickable (opens the profile menu) and
  // coloured like that name everywhere else; roles / orgs / System / Mysterious have no player to
  // act on, so they stay plain coloured text.
  const senderPlayer = $derived(
    typeof senderDisplay !== "string" && "Raw" in senderDisplay
      ? slotKeyToString(senderDisplay.Raw)
      : null,
  );
  // The sender's public status, shown beside their name in the header. Only a player has one.
  const senderStatuses = $derived(
    senderPlayer ? statusLabels(view.actor_statuses.get(senderPlayer) ?? 0) : [],
  );
</script>

<div
  class="px-4 pt-0.5 {grouped ? '' : 'mt-2 first:mt-0'} {last
    ? 'pb-1.5'
    : 'pb-0.5'} {mentioned
    ? 'bg-amber-400/10 shadow-[inset_2px_0_0_rgba(251,191,36,0.8)]'
    : 'hover:bg-neutral-800/40'}"
>
  {#if !grouped}
    <div class="flex items-baseline justify-between gap-2">
      <div class="flex min-w-0 items-baseline gap-2">
        {#if senderPlayer}
          <Name id={senderPlayer} {view} />
        {:else}
          <span class="font-medium" style="color: {senderColor}">{senderLabel}</span>
        {/if}
        {#each senderStatuses as s (s)}
          <span
            class="rounded px-1 py-px text-[0.6rem] uppercase tracking-wide"
            style={statusBadgeStyle(s)}
          >{s}</span>
        {/each}
      </div>
      <TimeStamp {timestamp} {view} />
    </div>
  {/if}
  <div class="flex items-baseline gap-2">
    <div class="min-w-0 flex-1 whitespace-pre-wrap break-words text-sm text-neutral-300">
      <MentionText {content} {view} />
    </div>
    {#if grouped}
      <!-- A grouped message drops the sender header, but every message still carries its own moment:
           the timestamp stays beside the line so a continuation reads its own time. -->
      <TimeStamp {timestamp} {view} />
    {/if}
  </div>
</div>

// amane/amane-ui/game/channels/Message.tsx
// The sender resolves against the view — rendered via the shared Entity component, so the header
// matches how that name renders everywhere else. Content still carries raw mention tokens, which
// MentionText resolves against the same view.
//
// `grouped` only drops the sender header for a continuation of an uninterrupted run from the same
// sender. Every row stays its own hover target and carries its own time.
import type { ActorDisplay } from "amane-client/bindings.ts";
import { slotKeyToString } from "amane-client/bindings.ts";
import type { View } from "amane-client/game/view.ts";
import { refFromDisplay, statusLabels } from "amane-client/text.ts";
import { statusAccent, tint } from "../../style.ts";
import { Entity, TimeStamp } from "../Name.tsx";
import { MentionText } from "../mentions/MentionText.tsx";

export function Message({
  senderDisplay,
  content,
  view,
  timestamp,
  grouped = false,
  mentioned = false,
  last = false,
}: {
  senderDisplay: ActorDisplay;
  content: string;
  view: View;
  timestamp: number;
  grouped?: boolean;
  // Whether this message names the viewer. Tints the whole row and keeps the tint on hover, rather
  // than the ordinary hover highlight, so a ping stands out in a busy channel.
  mentioned?: boolean;
  // Last message of its chain — the next row is a different sender, a non-message, or nothing. Only
  // the tail of a chain carries the block's bottom spacing, so a header isn't shoved away from its
  // own continuation lines.
  last?: boolean;
}) {
  // The sender's public status, shown beside their name in the header. Only a player has one.
  const senderPlayer = senderDisplay !== "Mysterious" && senderDisplay !== "System" && "Raw" in senderDisplay
    ? slotKeyToString(senderDisplay.Raw)
    : null;
  const senderStatuses = senderPlayer ? statusLabels(view.actor_statuses.get(senderPlayer) ?? 0) : [];

  // The ping tint reuses the "stands out" accent already meant for exactly that (a bugged badge),
  // rather than the button accent, which means something else entirely.
  const pingColor = "var(--color-status-bugged)";
  return (
    <div
      className={`px-4 pt-0.5 ${grouped ? "" : "mt-2 first:mt-0"} ${last ? "pb-1.5" : "pb-0.5"} ${mentioned ? "" : "hover:bg-raised/40"}`}
      style={
        mentioned
          ? { backgroundColor: `color-mix(in srgb, ${pingColor} 10%, transparent)`, boxShadow: `inset 2px 0 0 ${pingColor}` }
          : undefined
      }
    >
      {!grouped && (
        <div className="flex items-baseline justify-between gap-2">
          <div className="flex min-w-0 items-baseline gap-2">
            <Entity of={refFromDisplay(senderDisplay, view.orgs)} view={view} chip />
            {senderStatuses.map((s) => (
              <span key={s} className="px-1 py-px text-xs uppercase tracking-wide" style={tint(statusAccent(s))}>
                {s}
              </span>
            ))}
          </div>
          <TimeStamp timestamp={timestamp} />
        </div>
      )}
      <div className="flex items-baseline gap-2">
        <div className="min-w-0 flex-1 whitespace-pre-wrap break-words text-sm text-ink">
          <MentionText content={content} view={view} />
        </div>
        {grouped && (
          // A grouped message drops the sender header, but every message still carries its own
          // moment: the timestamp stays beside the line so a continuation reads its own time.
          <TimeStamp timestamp={timestamp} />
        )}
      </div>
    </div>
  );
}
