// amane/amane-ui/game/PlayerSelect.tsx
// A player picker for anything that takes a target. Offers only the players this view has been
// told about: a target you have never heard of is not one you get to name. The engine is the
// authority on which targets are valid.
import { playerLabel } from "amane-client/text.ts";
import { useView } from "./game_ui.ts";

export function PlayerSelect({
  value,
  onChange,
  placeholder = "Select a player",
  ids,
}: {
  value: string;
  onChange: (id: string) => void;
  placeholder?: string;
  // Only these players (e.g. an org's members). Omitted: every player the view knows.
  ids?: Iterable<string>;
}) {
  const view = useView();
  const allowed = ids ? new Set(ids) : null;
  const players = [...view.players.keys()].filter((id) => !allowed || allowed.has(id));
  return (
    <select
      value={value}
      onChange={(event) => onChange(event.target.value)}
      className="h-9 w-full min-w-0 border border-edge bg-panel px-2 text-sm text-ink"
    >
      <option value="" disabled>
        {placeholder}
      </option>
      {players.map((id) => (
        <option key={id} value={id}>
          {playerLabel(id, view.players)}
        </option>
      ))}
    </select>
  );
}

// amane/ui/game/abilities/PlayerSelect.svelte
<script lang="ts">
  // A plain player picker for target-taking abilities. Binds the selected player's
  // string key. The engine is the authority on valid targets (self-target, etc.), so
  // every player is offered here.
  import { getContext } from "svelte";
  import { GAME_STATE_KEY, playerLabel } from "../../../game_state.svelte.ts";
  import type { GameState } from "../../../game_state.svelte.ts";

  let {
    value = $bindable(""),
    placeholder = "Select a player",
    ids = undefined,
  }: {
    value?: string;
    placeholder?: string;
    // Optional allowlist: when set, only these player ids are offered (e.g. an org's members).
    // Omitted = every player, since the engine is the authority on valid targets.
    ids?: Iterable<string>;
  } = $props();

  const game = getContext<GameState>(GAME_STATE_KEY);
  const allowed = $derived(ids ? new Set(ids) : null);
  const players = $derived(
    [...game.players.entries()].filter(([id]) => !allowed || allowed.has(id)),
  );
</script>

<select
  bind:value
  class="w-full rounded-md border border-edge bg-panel px-2 py-2 text-sm text-ink"
>
  <option value="" disabled>{placeholder}</option>
  {#each players as [id] (id)}
    <option value={id}>{playerLabel(id, game.players)}</option>
  {/each}
</select>
