// armonia/src/ui/game/GcControls.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { GAME_STATE_KEY } from "../../game_state.svelte.ts";
  import { UI_STATE_KEY } from "../../ui_state.svelte.ts";
  import { now } from "../../time.svelte.ts";
  import type { GameState } from "../../game_state.svelte.ts";
  import type { UiState } from "../../ui_state.svelte.ts";
  import type { ActionRequest, ActionPayload } from "../../bindings";
  import { slotKeyFromString, slotKeyToString } from "../../bindings";
  import { viewerToActor } from "../../types";
  import { Flash } from "../../flash.svelte.ts";
  import FlashDisplay from "../Flash.svelte";

  const game = getContext<GameState>(GAME_STATE_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);

  const flash = new Flash();
  let open = $state(false);

  // The selected channel's backing gc, if it is a group chat at all.
  const gc_key = $derived(
    ui.selected_channel
      ? game.gc_key_for_channel(ui.selected_channel)
      : undefined,
  );

  // Only the gc's owner sees the controls. Admin has no view, so it's never owner.
  const is_owner = $derived(
    !!gc_key && (game.views.get(ui.viewer)?.owned_gcs.has(gc_key) ?? false),
  );

  // Current members the owner can act on: Raw displays only (a specific player), and
  // never the owner themselves. Role/anonymous members can't be targeted by id.
  const members = $derived.by(() => {
    if (!ui.selected_channel) return [];
    const entry = game.views.get(ui.viewer)?.channel_views.get(ui.selected_channel);
    const out: { id: string; name: string }[] = [];
    for (const [, m] of entry?.members ?? []) {
      const d = m.display;
      if (!m.had_positive) continue;
      if (typeof d !== "string" && "Raw" in d) {
        const id = slotKeyToString(d.Raw);
        if (id === ui.viewer) continue;
        out.push({ id, name: game.resolve_display(d) });
      }
    }
    return out;
  });

  const member_ids = $derived(new Set(members.map((m) => m.id)));

  // Players not already members (and not the owner) — candidates to add.
  const candidates = $derived(
    [...game.players.entries()].filter(
      ([id]) => id !== ui.viewer && !member_ids.has(id),
    ),
  );

  async function send(payload: ActionPayload, ok: string) {
    const request: ActionRequest = {
      actor: viewerToActor(ui.viewer),
      timestamp: now(),
      payload,
    };
    const err = await game.dispatch(request);
    if (err) flash.set_error(err);
    else flash.set_success(ok);
  }

  function add(player_id: string) {
    if (!gc_key) return;
    send(
      {
        AddToGroupchat: {
          groupchat_id: slotKeyFromString(gc_key),
          player_id: slotKeyFromString(player_id),
          owner: false,
        },
      },
      "Added.",
    );
  }

  function remove(player_id: string) {
    if (!gc_key) return;
    send(
      {
        RemoveFromGroupchat: {
          groupchat_id: slotKeyFromString(gc_key),
          player_id: slotKeyFromString(player_id),
        },
      },
      "Removed.",
    );
  }

  function transfer(player_id: string) {
    if (!gc_key) return;
    send(
      {
        SetGroupchatOwner: {
          groupchat_id: slotKeyFromString(gc_key),
          owner: slotKeyFromString(player_id),
        },
      },
      "Ownership transferred.",
    );
  }
</script>

{#if is_owner}
  <div class="flex flex-col gap-1 border-b border-neutral-800 p-2">
    <button
      class="flex items-center gap-1 px-2 py-1 text-xs font-medium uppercase tracking-wide text-neutral-400 hover:text-neutral-200"
      onclick={() => (open = !open)}
    >
      <span class="text-[0.6rem]">{open ? "▾" : "▸"}</span>
      Group Chat Controls
    </button>

    {#if open}
      <!-- Add a member -->
      <p class="px-2 pt-1 text-[0.65rem] uppercase tracking-wide text-neutral-600">
        Add member
      </p>
      {#if candidates.length === 0}
        <p class="px-2 py-1 text-xs text-neutral-600">No one to add</p>
      {:else}
        {#each candidates as [id, player] (id)}
          <button
            class="flex w-full items-center justify-between rounded px-2 py-1 text-sm text-neutral-300 hover:bg-neutral-800"
            onclick={() => add(id)}
          >
            <span>{player.display_name}</span>
            <span class="text-xs text-neutral-600">add</span>
          </button>
        {/each}
      {/if}

      <!-- Existing members: remove or hand ownership -->
      <p class="px-2 pt-2 text-[0.65rem] uppercase tracking-wide text-neutral-600">
        Members
      </p>
      {#if members.length === 0}
        <p class="px-2 py-1 text-xs text-neutral-600">No other members</p>
      {:else}
        {#each members as m (m.id)}
          <div
            class="flex items-center justify-between gap-1 rounded px-2 py-1 text-sm text-neutral-300"
          >
            <span class="truncate">{m.name}</span>
            <span class="flex shrink-0 gap-1">
              <button
                class="rounded px-1.5 py-0.5 text-xs text-neutral-400 hover:bg-neutral-800 hover:text-neutral-200"
                onclick={() => transfer(m.id)}
                title="Make owner"
              >
                owner
              </button>
              <button
                class="rounded px-1.5 py-0.5 text-xs text-red-400/80 hover:bg-neutral-800 hover:text-red-300"
                onclick={() => remove(m.id)}
                title="Remove from group chat"
              >
                remove
              </button>
            </span>
          </div>
        {/each}
      {/if}

      <div class="px-2 pt-1">
        <FlashDisplay {flash} />
      </div>
    {/if}
  </div>
{/if}

// amane/amane-ui/game/side/GcControls.tsx
// The group chat owner's controls for the selected channel: add a member, remove one, or hand off
// ownership. Renders nothing unless the selected channel is a group chat this view owns.
import type { Action } from "amane-client/bindings.ts";
import { slotKeyFromString, slotKeyToString } from "amane-client/bindings.ts";
import { viewActor } from "amane-client/queries/session.ts";
import { refFromDisplay, refLabel } from "amane-client/text.ts";
import { useSession } from "../../hooks.ts";
import { Button } from "../../kit/Button.tsx";
import { FlashLine, useFlash } from "../../kit/Flash.tsx";
import { Section } from "../../kit/Section.tsx";
import { useGameUi, useView } from "../game_ui.ts";
import { Entity } from "../Name.tsx";

export function GcControls() {
  const ui = useGameUi();
  const view = useView();
  const session = useSession();
  const flash = useFlash();

  const channelId = ui.selected?.kind === "channel" ? ui.selected.id : null;
  const link = channelId ? view.channels.get(channelId)?.link : null;
  const gcKey = link && "gc" in link ? link.gc : null;
  const isOwner = gcKey !== null && view.owned_gcs.has(gcKey);
  if (!gcKey || !isOwner) return null;

  const members: { id: string; name: string }[] = [];
  for (const profile of view.channel_views.get(channelId!)?.roster ?? []) {
    const d = profile.display;
    if (typeof d !== "string" && "Raw" in d) {
      const id = slotKeyToString(d.Raw);
      if (id === ui.viewer) continue;
      members.push({ id, name: refLabel(refFromDisplay(d, view.orgs), view.players) });
    }
  }
  const memberIds = new Set(members.map((m) => m.id));
  const candidates = [...view.players.keys()].filter((id) => id !== ui.viewer && !memberIds.has(id));

  async function send(payload: Action, ok: string) {
    const reply = await session.submit_action({ actor: viewActor(ui.viewer), timestamp: Date.now(), payload });
    flash.reply(reply, ok);
  }
  function add(playerId: string) {
    send(
      { AddToGroupchat: { groupchat_id: slotKeyFromString(gcKey!), player_id: slotKeyFromString(playerId), owner: false } },
      "Added.",
    );
  }
  function remove(playerId: string) {
    send(
      { RemoveFromGroupchat: { groupchat_id: slotKeyFromString(gcKey!), player_id: slotKeyFromString(playerId) } },
      "Removed.",
    );
  }
  function transfer(playerId: string) {
    send(
      { SetGroupchatOwner: { groupchat_id: slotKeyFromString(gcKey!), owner: slotKeyFromString(playerId) } },
      "Ownership transferred.",
    );
  }

  return (
    <Section label="Group Chat Controls">
      <p className="px-3 pt-2 pb-0.5 text-xs font-medium uppercase tracking-wide text-ink-dim">Add member</p>
      {candidates.length === 0 ? (
        <p className="px-3 py-1 text-sm text-ink-dim">No one to add</p>
      ) : (
        candidates.map((id) => (
          <button
            key={id}
            type="button"
            className="flex min-h-8 w-full items-center justify-between px-3 py-1.5 text-sm text-ink hover:bg-raised"
            onClick={() => add(id)}
          >
            <span className="min-w-0 truncate">
              <Entity of={{ kind: "player", id }} view={view} menu={false} />
            </span>
            <span className="shrink-0 text-sm text-ink-dim">add</span>
          </button>
        ))
      )}

      <p className="px-3 pt-2 pb-0.5 text-xs font-medium uppercase tracking-wide text-ink-dim">Members</p>
      {members.length === 0 ? (
        <p className="px-3 py-1 text-sm text-ink-dim">No other members</p>
      ) : (
        members.map((m) => (
          <div key={m.id} className="flex flex-wrap items-center justify-between gap-2 px-3 py-1.5 text-sm text-ink">
            <span className="min-w-0 truncate">{m.name}</span>
            <span className="flex shrink-0 gap-1">
              <Button variant="ghost" size="sm" title="Make owner" onClick={() => transfer(m.id)}>
                owner
              </Button>
              <Button variant="danger" size="sm" title="Remove from group chat" onClick={() => remove(m.id)}>
                remove
              </Button>
            </span>
          </div>
        ))
      )}

      <div className="px-3 py-1.5">
        <FlashLine flash={flash} />
      </div>
    </Section>
  );
}
