// amane/amane-core/ui/game/OrgPanel.svelte
<script lang="ts">
  import { execErrorText } from "../../game/helpers.svelte";
  import { getContext } from "svelte";
  import { GAME_STATE_KEY } from "../../game/state.svelte";
  import {
    orgColorVar,
    orgDisplayName,
    playerLabel,
  } from "../../game/helpers.svelte";
  import { SESSION_KEY, type SessionState } from "../../session.svelte.ts";
  import { UI_STATE_KEY } from "../../ui_state.svelte.ts";
  import { now } from "../../time.svelte.ts";
  import type { GameState } from "../../game/state.svelte";
  import type { UiState } from "../../ui_state.svelte.ts";
  import type { Action } from "../../bindings";
  import { slotKeyFromString } from "../../bindings";
  import { viewerToActor } from "../../types";
  import { Flash } from "../../flash.svelte.ts";
  import FlashDisplay from "../Flash.svelte";
  import AbilityMenu from "./abilities/AbilityMenu.svelte";
  import Dialog from "../kit/Dialog.svelte";
  import Button from "../kit/Button.svelte";
  import Name from "./Name.svelte";

  const game = getContext<GameState>(GAME_STATE_KEY);

  const session = getContext<SessionState>(SESSION_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);
  // The one view this component renders. Everything it can show is what this view was delivered.
  const view = $derived(game.view_of(ui.viewer));

  let open = $state(false);
  const flash = new Flash();

  // The org backing the selected channel, if it's an org channel.
  const org_key = $derived(
    ui.selected_channel
      ? view.org_of_channel(ui.selected_channel)
      : undefined,
  );
  const org = $derived(org_key ? view.orgs.get(org_key) : undefined);

  // Holding the org at all is the gate: it is here because this view was delivered its MapActor.
  const visible = $derived(!!org);

  // The org's members and abilities ride its channel's viewport, so losing that viewport stops
  // both. What is on screen is then the roster as it last stood, which is worth saying out loud —
  // an org you were thrown out of does not stop having members, you just stop hearing about them.
  const frozen = $derived(
    !!org && view.frozen(view.viewport_of(ui.selected_channel ?? "")),
  );

  // Gates ACTING, where `visible` above gates showing: a former member should still see the org,
  // just not be offered its abilities. UX, not security — the engine rejects the action regardless.
  const is_member = $derived(
    ui.viewer === "Admin" || (!!org && org.members.has(ui.viewer)),
  );

  // The full list; every member sees it. `effective` marks the present members — the ones who
  // count toward the org's ability member requirements. An absent member (kidnapped, jailed, dead)
  // stays listed and acts like a normal member, but does not count, so the org sees its real reach.
  const org_members = $derived(
    [...(org?.members ?? [])].map((id) => ({
      id,
      name: playerLabel(id, view.players),
      effective: org?.effective.has(id) ?? false,
    })),
  );
  const effective_count = $derived(org_members.filter((m) => m.effective).length);

  // As far as THIS view is entitled to know, which needs no check of who is looking: OG standing
  // reaches the member and System and nobody else, so `player_info` is populated only on System
  // and `og_orgs` holds only your own. A view asked about anyone else answers no.
  function is_og(id: string): boolean {
    if (!org_key) return false;
    if (view.player_info.get(id)?.og_orgs?.has(org_key)) return true;
    return id === ui.viewer && view.og_orgs.has(org_key);
  }

  // Admin-only: players not already in the org.
  const candidates = $derived(
    [...view.players.entries()].filter(([id]) => !org?.members.has(id)),
  );

  // Applied to the next add. `leader` requires the org to have leadership at all.
  let add_leader = $state(false);
  let add_og = $state(false);

  async function send(payload: Action, ok: string) {
    const reply = await session.submit_action({
      actor: viewerToActor(ui.viewer),
      timestamp: now(),
      payload,
    });
    if (!reply.ok) flash.set_error(execErrorText(reply.error));
    else flash.set_success(ok);
  }

  function add_member(player_id: string) {
    if (!org_key) return;
    send(
      {
        AddToOrg: {
          actor_id: slotKeyFromString(player_id),
          org_id: slotKeyFromString(org_key),
          leader: add_leader,
          og: add_og,
        },
      },
      "Added.",
    );
  }

  function remove_member(player_id: string) {
    if (!org_key) return;
    send(
      {
        RemoveFromOrg: {
          actor_id: slotKeyFromString(player_id),
          org_id: slotKeyFromString(org_key),
        },
      },
      "Removed.",
    );
  }

  function toggle_og(player_id: string) {
    if (!org_key) return;
    send(
      {
        SetOgStatus: {
          actor_id: slotKeyFromString(player_id),
          org_id: slotKeyFromString(org_key),
          og: !is_og(player_id),
        },
      },
      "OG status updated.",
    );
  }

  // No blacklist control here on purpose: it is a low-level primitive that other machinery drives
  // (silent prosecution). An org cannot bar or unbar anyone, so offering it on the org's own
  // roster would teach the wrong model of what it is.
</script>

{#if visible && org && org_key}
  {@const accent = orgColorVar(org.name)}

  <Button variant="ghost" size="sm" class="w-full justify-start" onclick={() => (open = true)}>
    Organization
  </Button>

  {#snippet head()}
    <span class="flex items-center gap-2.5">
      <span class="h-3 w-3 shrink-0" style="background-color:{accent}"></span>
      <span class="text-lg font-semibold" style="color:{accent}">{orgDisplayName(org.name)}</span>
      <span class="text-[0.7rem] font-normal uppercase tracking-widest text-ink-dim">Organization</span>
    </span>
  {/snippet}

  <Dialog bind:open header={head} class="max-w-lg">
    <div class="flex flex-col divide-y divide-edge">
      <!-- frozen outranks is_member, because is_member reads the global roster and the roster is
           one of the things that stopped updating. A view that has lost the viewport can still be
           listed in an org it was thrown out of. -->
      <div class="pb-4">
        {#if frozen}
          <p class="border-l-2 border-event-alarm bg-event-alarm/10 px-3 py-2 text-xs text-event-alarm">
            This organization no longer reaches you. Everything here is what you last saw.
          </p>
        {:else if is_member}
          <AbilityMenu orgId={org_key} />
        {:else}
          <p class="border-l-2 border-edge bg-raised px-3 py-2 text-xs text-ink-dim">
            You are no longer in this organization. Everything here is what you last saw.
          </p>
        {/if}
      </div>

      <div class="flex flex-col gap-2 py-4">
        <div class="flex items-baseline justify-between gap-2">
          <span class="text-[0.7rem] font-semibold uppercase tracking-widest text-neutral-400">Members</span>
          <span class="text-[0.7rem] tabular-nums text-ink-dim">
            <span class="text-neutral-300">{org_members.length}</span> total
            ·
            <span style="color:{accent}">{effective_count}</span> counted
          </span>
        </div>

        {#if org_members.length === 0}
          <p class="py-1 text-xs text-ink-dim">No members.</p>
        {:else}
          <div class="border border-edge">
            {#each org_members as m (m.id)}
              <div class="flex items-center gap-2 border-b border-edge px-3 py-2 last:border-b-0">
                <span class="min-w-0 flex-1 truncate text-sm {m.effective ? 'text-ink' : 'text-neutral-500'}">
                  {m.name}
                </span>
                {#if !m.effective}
                  <span
                    class="shrink-0 border border-edge px-1.5 py-0.5 text-[0.6rem] font-medium uppercase tracking-wide text-neutral-400"
                    title="Not present, so not counted toward this org's ability member requirements. Still a full member."
                  >
                    not counted
                  </span>
                {/if}
                {#if is_og(m.id)}
                  <span
                    class="shrink-0 border px-1.5 py-0.5 text-[0.6rem] font-semibold uppercase tracking-wide"
                    style="color:{accent};border-color:{accent}"
                    title="An original member. Only they and the host know this."
                  >
                    OG
                  </span>
                {/if}
                {#if ui.viewer === "Admin"}
                  <button
                    class="shrink-0 border border-edge px-2 py-0.5 text-[0.65rem] uppercase tracking-wide text-neutral-400 hover:border-neutral-500 hover:text-ink"
                    onclick={() => toggle_og(m.id)}
                    title="Toggle OG status"
                  >
                    og
                  </button>
                  <button
                    class="shrink-0 border border-edge px-2 py-0.5 text-[0.65rem] uppercase tracking-wide text-danger hover:border-danger hover:bg-danger/10"
                    onclick={() => remove_member(m.id)}
                    title="Remove from org"
                  >
                    remove
                  </button>
                {/if}
              </div>
            {/each}
          </div>
        {/if}
      </div>

      {#if ui.viewer === "Admin"}
        <div class="flex flex-col gap-2 pt-4">
          <div class="flex items-center justify-between gap-2">
            <span class="text-[0.7rem] font-semibold uppercase tracking-widest text-neutral-400">Add member</span>
            <div class="flex gap-3 text-xs text-neutral-300">
              <label class="flex items-center gap-1.5">
                <input type="checkbox" bind:checked={add_leader} /> leader
              </label>
              <label class="flex items-center gap-1.5">
                <input type="checkbox" bind:checked={add_og} /> og
              </label>
            </div>
          </div>

          {#if candidates.length === 0}
            <p class="py-1 text-xs text-ink-dim">No one to add.</p>
          {:else}
            <div class="border border-edge">
              {#each candidates as [id] (id)}
                <button
                  class="flex w-full items-center justify-between border-b border-edge px-3 py-2 text-sm text-ink last:border-b-0 hover:bg-raised"
                  onclick={() => add_member(id)}
                >
                  <span class="truncate"><Name {id} {view} menu={false} /></span>
                  <span class="shrink-0 text-[0.65rem] uppercase tracking-wide text-ink-dim">add</span>
                </button>
              {/each}
            </div>
          {/if}
          <FlashDisplay {flash} />
        </div>
      {/if}
    </div>
  </Dialog>
{/if}

// amane/amane-ui/game/side/OrgPanel.tsx
// The selected channel's organization, opened from a rail button: its abilities (via AbilityMenu),
// its roster, and — for System — membership controls. Renders nothing unless the selected channel
// backs an org this view was told about.
import { useState } from "react";
import type { Action } from "amane-client/bindings.ts";
import { slotKeyFromString } from "amane-client/bindings.ts";
import { orgMembers, orgOfChannel } from "amane-client/queries/orgs.ts";
import { viewActor } from "amane-client/queries/session.ts";
import { orgDisplayName, playerLabel } from "amane-client/text.ts";
import { useSession } from "../../hooks.ts";
import { Button } from "../../kit/Button.tsx";
import { FlashLine, useFlash } from "../../kit/Flash.tsx";
import { Modal } from "../../kit/Modal.tsx";
import { orgColorVar, tint } from "../../style.ts";
import { useGameUi, useView } from "../game_ui.ts";
import { Entity } from "../Name.tsx";
import { AbilityMenu } from "../abilities/AbilityMenu.tsx";
import { RailButton } from "./RailButton.tsx";

export function OrgPanel() {
  const ui = useGameUi();
  const view = useView();
  const session = useSession();
  const flash = useFlash();
  const [open, setOpen] = useState(false);
  const [addLeader, setAddLeader] = useState(false);
  const [addOg, setAddOg] = useState(false);

  const channelId = ui.selected?.kind === "channel" ? ui.selected.id : null;
  const entry = orgOfChannel(view, channelId);
  if (!entry) return null;
  const [orgId, org] = entry;
  const accent = orgColorVar(org.name);
  const isAdmin = ui.viewer === "System";
  // The org's roster and abilities ride its own viewport. Frozen outranks membership below, since
  // membership reads the roster and the roster is one of the things that stopped updating — a view
  // that has lost the viewport can still be listed in an org it was thrown out of.
  const frozen = view.frozen(org.viewport);
  const isMember = isAdmin || org.members.has(ui.viewer);
  const members = orgMembers(view, orgId, org);
  const effectiveCount = members.filter((m) => m.effective).length;
  const candidates = [...view.players.keys()].filter((id) => !org.members.has(id));

  async function send(payload: Action, ok: string) {
    const reply = await session.submit_action({ actor: viewActor(ui.viewer), timestamp: Date.now(), payload });
    flash.reply(reply, ok);
  }
  function addMember(playerId: string) {
    send(
      { AddToOrg: { actor_id: slotKeyFromString(playerId), org_id: slotKeyFromString(orgId), leader: addLeader, og: addOg } },
      "Added.",
    );
  }
  function removeMember(playerId: string) {
    send({ RemoveFromOrg: { actor_id: slotKeyFromString(playerId), org_id: slotKeyFromString(orgId) } }, "Removed.");
  }
  function toggleOg(playerId: string, currentlyOg: boolean) {
    send({ SetOgStatus: { actor_id: slotKeyFromString(playerId), org_id: slotKeyFromString(orgId), og: !currentlyOg } }, "OG status updated.");
  }
  function toggleLeader(playerId: string, currentlyLeader: boolean) {
    send(
      { ChangeOrgLeader: { org_id: slotKeyFromString(orgId), new_leader: currentlyLeader ? null : slotKeyFromString(playerId) } },
      "Leader updated.",
    );
  }

  return (
    <>
      <RailButton active={open} onClick={() => setOpen(true)}>
        Organization
      </RailButton>

      <Modal
        open={open}
        onClose={() => setOpen(false)}
        width="32rem"
        title={
          <span className="flex items-center gap-2.5">
            <span className="h-3 w-3 shrink-0" style={{ backgroundColor: accent }} />
            <span style={{ color: accent }}>{orgDisplayName(org.name)}</span>
          </span>
        }
      >
        <div className="flex flex-col divide-y divide-edge">
          <div className="pb-4">
            {frozen ? (
              <p className="border-l-2 px-3 py-2 text-sm" style={tint("var(--color-event-alarm)")}>
                This organization no longer reaches you. Everything here is what you last saw.
              </p>
            ) : isMember ? (
              <AbilityMenu orgId={orgId} />
            ) : (
              <p className="border-l-2 border-edge bg-raised px-3 py-2 text-sm text-ink-dim">
                You are no longer in this organization. Everything here is what you last saw.
              </p>
            )}
          </div>

          <div className="flex flex-col gap-2 py-4">
            <div className="flex items-baseline justify-between gap-2">
              <span className="text-xs font-semibold uppercase tracking-widest text-ink-dim">Members</span>
              <span className="text-xs tabular-nums text-ink-dim">
                <span className="text-ink">{members.length}</span> total ·{" "}
                <span style={{ color: accent }}>{effectiveCount}</span> counted
              </span>
            </div>

            {members.length === 0 ? (
              <p className="py-1 text-sm text-ink-dim">No members.</p>
            ) : (
              <div className="flex flex-col border border-edge">
                {members.map((m) => (
                  <div key={m.id} className="flex flex-wrap items-center gap-2 border-b border-edge px-3 py-2 last:border-b-0">
                    <span className={`min-w-0 flex-1 truncate text-sm ${m.effective ? "text-ink" : "text-ink-dim"}`}>
                      {playerLabel(m.id, view.players)}
                    </span>
                    {!m.effective && (
                      <span
                        className="shrink-0 border border-edge px-1.5 py-0.5 text-xs font-medium uppercase tracking-wide text-ink-dim"
                        title="Not present, so not counted toward this org's ability member requirements. Still a full member."
                      >
                        not counted
                      </span>
                    )}
                    {m.leader && (
                      <span
                        className="shrink-0 border px-1.5 py-0.5 text-xs font-semibold uppercase tracking-wide"
                        style={{ color: accent, borderColor: accent }}
                        title="The org's leader. Only they and the host are told who this is."
                      >
                        Leader
                      </span>
                    )}
                    {m.og && (
                      <span
                        className="shrink-0 border px-1.5 py-0.5 text-xs font-semibold uppercase tracking-wide"
                        style={{ color: accent, borderColor: accent }}
                        title="An original member. Only they and the host know this."
                      >
                        OG
                      </span>
                    )}
                    {isAdmin && (
                      <span className="flex shrink-0 gap-1">
                        <Button variant="ghost" size="sm" title="Toggle leader" onClick={() => toggleLeader(m.id, m.leader)}>
                          leader
                        </Button>
                        <Button variant="ghost" size="sm" title="Toggle OG status" onClick={() => toggleOg(m.id, m.og)}>
                          og
                        </Button>
                        <Button variant="danger" size="sm" title="Remove from org" onClick={() => removeMember(m.id)}>
                          remove
                        </Button>
                      </span>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {isAdmin && (
            <div className="flex flex-col gap-2 pt-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <span className="text-xs font-semibold uppercase tracking-widest text-ink-dim">Add member</span>
                <div className="flex gap-3 text-xs text-ink">
                  <label className="flex items-center gap-1.5">
                    <input type="checkbox" checked={addLeader} onChange={(e) => setAddLeader(e.target.checked)} /> leader
                  </label>
                  <label className="flex items-center gap-1.5">
                    <input type="checkbox" checked={addOg} onChange={(e) => setAddOg(e.target.checked)} /> og
                  </label>
                </div>
              </div>

              {candidates.length === 0 ? (
                <p className="py-1 text-sm text-ink-dim">No one to add.</p>
              ) : (
                <div className="flex flex-col border border-edge">
                  {candidates.map((id) => (
                    <button
                      key={id}
                      type="button"
                      className="flex min-h-8 w-full items-center justify-between border-b border-edge px-3 py-2 text-sm text-ink last:border-b-0 hover:bg-raised"
                      onClick={() => addMember(id)}
                    >
                      <Entity of={{ kind: "player", id }} view={view} menu={false} />
                      <span className="shrink-0 text-xs uppercase tracking-wide text-ink-dim">add</span>
                    </button>
                  ))}
                </div>
              )}
              <FlashLine flash={flash} />
            </div>
          )}
        </div>
      </Modal>
    </>
  );
}
