// client/amane/ui/game/OrgPanel.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { GAME_STATE_KEY, playerLabel } from "../../game_state.svelte.ts";
  import { CLIENT_KEY, type ClientState } from "../../client.svelte.ts";
  import { UI_STATE_KEY } from "../../ui_state.svelte.ts";
  import { now } from "../../time.svelte.ts";
  import type { GameState } from "../../game_state.svelte.ts";
  import type { UiState } from "../../ui_state.svelte.ts";
  import type { Action } from "../../bindings";
  import { slotKeyFromString } from "../../bindings";
  import { viewerToActor } from "../../types";
  import { Flash } from "../../flash.svelte.ts";
  import FlashDisplay from "../Flash.svelte";
  import AbilityMenu from "./abilities/AbilityMenu.svelte";

  const game = getContext<GameState>(GAME_STATE_KEY);

  const client = getContext<ClientState>(CLIENT_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);

  let open = $state(true);
  const flash = new Flash();

  // The org backing the selected channel, if it's an org channel.
  const org_key = $derived(
    ui.selected_channel
      ? game.org_key_for_channel(ui.selected_channel)
      : undefined,
  );
  const org = $derived(org_key ? game.orgs.get(org_key) : undefined);

  // Only those who can view the org's channel (or admin) see the panel — matches the
  // sidebar's gating and the org-directed command delivery rule.
  const visible = $derived(
    !!org &&
      (ui.viewer === "Admin" ||
        (game.views.get(ui.viewer)?.channel_views.get(org.channel_id)?.perms
          ?.had_positive ??
          false)),
  );

  // Whether the viewer is in the org RIGHT NOW, which is a different question from `visible`
  // above. That one asks "were you ever here" and keeps the panel around as an archive of what you
  // knew; this asks "are you here", and it is what gates acting. A former member should still see
  // the org — just not be offered its abilities as though they were still in it.
  //
  // UX, not security: the engine rejects the action regardless. This only stops the client
  // presenting something it has no business offering.
  const is_member = $derived(
    ui.viewer === "Admin" || (!!org && org.members.has(ui.viewer)),
  );

  // Org members: the full list, everyone sees it. Resolved to display names.
  const org_members = $derived(
    [...(org?.members ?? [])].map((id) => ({
      id,
      name: playerLabel(id, game.players),
    })),
  );

  // Whether a member is an OG, as far as THIS viewer is entitled to know.
  //
  // OG standing is personal info: it goes to the member and to System, never to the rest of the
  // org. So admin reads anyone's out of player_info, a player can only ever answer for themselves,
  // and everyone else is shown nothing rather than a guess.
  function is_og(id: string): boolean {
    if (!org_key) return false;
    if (ui.viewer === "Admin") {
      return game.player_info.get(id)?.og_orgs?.has(org_key) ?? false;
    }
    return id === ui.viewer && (game.views.get(ui.viewer)?.og_orgs.has(org_key) ?? false);
  }

  // Admin-only: players not already in the org, to add via AddToOrg.
  const candidates = $derived(
    [...game.players.entries()].filter(([id]) => !org?.members.has(id)),
  );

  // Configuration applied to the next add: leader makes them the org leader (requires the
  // org to have leadership); og marks them an original/founding member.
  let add_leader = $state(false);
  let add_og = $state(false);

  async function send(payload: Action, ok: string) {
    const err = await client.dispatch({
      actor: viewerToActor(ui.viewer),
      timestamp: now(),
      payload,
    });
    if (err) flash.set_error(err);
    else flash.set_success(ok);
  }

  function add_member(player_id: string) {
    if (!org_key) return;
    send(
      {
        AddToOrg: {
          actor_id: slotKeyFromString(player_id),
          org_id: slotKeyFromString(org_key),
          leader: add_leader,
          og: add_og,
        },
      },
      "Added.",
    );
  }

  function remove_member(player_id: string) {
    if (!org_key) return;
    send(
      {
        RemoveFromOrg: {
          actor_id: slotKeyFromString(player_id),
          org_id: slotKeyFromString(org_key),
        },
      },
      "Removed.",
    );
  }

  function toggle_og(player_id: string) {
    if (!org_key) return;
    send(
      {
        SetOgStatus: {
          actor_id: slotKeyFromString(player_id),
          org_id: slotKeyFromString(org_key),
          og: !is_og(player_id),
        },
      },
      "OG status updated.",
    );
  }

  // No blacklist control here on purpose. Blacklisting is a low-level primitive that other
  // machinery drives (silent prosecution); an org cannot bar or unbar anyone, so offering it in the
  // org's own roster would teach the wrong model of what it is.
</script>

{#if visible && org && org_key}
  <div class="flex flex-col gap-1 border-b border-neutral-800 p-2">
    <button
      class="flex items-center gap-1 px-2 py-1 text-xs font-medium uppercase tracking-wide text-neutral-400 hover:text-neutral-200"
      onclick={() => (open = !open)}
    >
      <span class="text-[0.6rem]">{open ? "▾" : "▸"}</span>
      Organization
    </button>

    {#if open}
      <div class="px-2 pt-1">
        {#if is_member}
          <AbilityMenu orgId={org_key} />
        {:else}
          <p class="text-xs text-neutral-600">
            You are no longer in this organization. Everything here is what you last saw.
          </p>
        {/if}
      </div>

      <p class="px-2 pt-2 text-[0.65rem] uppercase tracking-wide text-neutral-600">
        Members ({org_members.length})
      </p>
      {#if org_members.length === 0}
        <p class="px-2 py-1 text-xs text-neutral-600">No members</p>
      {:else}
        {#each org_members as m (m.id)}
          <div class="flex items-center justify-between gap-1 rounded px-2 py-1 text-sm text-neutral-300">
            <span class="truncate">{m.name}</span>
            {#if is_og(m.id)}
              <span
                class="shrink-0 rounded bg-violet-600/20 px-1.5 py-0.5 text-[0.65rem] font-medium text-violet-300"
                title="An original member. Only they and the host know this."
              >
                OG
              </span>
            {/if}
            <span class="flex-1"></span>
            {#if ui.viewer === "Admin"}
              <button
                class="shrink-0 rounded px-1.5 py-0.5 text-xs text-violet-400/80 hover:bg-neutral-800 hover:text-violet-300"
                onclick={() => toggle_og(m.id)}
                title="Toggle OG status"
              >
                og
              </button>
              <button
                class="shrink-0 rounded px-1.5 py-0.5 text-xs text-red-400/80 hover:bg-neutral-800 hover:text-red-300"
                onclick={() => remove_member(m.id)}
                title="Remove from org"
              >
                remove
              </button>
            {/if}
          </div>
        {/each}
      {/if}

      {#if ui.viewer === "Admin"}
        <p class="px-2 pt-2 text-[0.65rem] uppercase tracking-wide text-neutral-600">
          Add member
        </p>
        <div class="flex gap-3 px-2 py-1 text-xs text-neutral-400">
          <label class="flex items-center gap-1">
            <input type="checkbox" bind:checked={add_leader} /> leader
          </label>
          <label class="flex items-center gap-1">
            <input type="checkbox" bind:checked={add_og} /> og
          </label>
        </div>
        {#if candidates.length === 0}
          <p class="px-2 py-1 text-xs text-neutral-600">No one to add</p>
        {:else}
          {#each candidates as [id] (id)}
            <button
              class="flex w-full items-center justify-between rounded px-2 py-1 text-sm text-neutral-300 hover:bg-neutral-800"
              onclick={() => add_member(id)}
            >
              <span>{playerLabel(id, game.players)}</span>
              <span class="text-xs text-neutral-600">add</span>
            </button>
          {/each}
        {/if}
        <div class="px-2 pt-1">
          <FlashDisplay {flash} />
        </div>
      {/if}
    {/if}
  </div>
{/if}

// amane/amane-ui/game/side/OrgPanel.tsx
// The selected channel's organization, opened from a rail button: its abilities (via AbilityMenu),
// its roster, and — for System — membership controls. Renders nothing unless the selected channel
// backs an org this view was told about.
import { useState } from "react";
import type { Action } from "amane-client/bindings.ts";
import { slotKeyFromString } from "amane-client/bindings.ts";
import { orgMembers, orgOfChannel } from "amane-client/queries/orgs.ts";
import { viewActor } from "amane-client/queries/session.ts";
import { orgDisplayName, playerLabel } from "amane-client/text.ts";
import { useSession } from "../../hooks.ts";
import { Button } from "../../kit/Button.tsx";
import { FlashLine, useFlash } from "../../kit/Flash.tsx";
import { Modal } from "../../kit/Modal.tsx";
import { orgColorVar, tint } from "../../style.ts";
import { useGameUi, useView } from "../game_ui.ts";
import { Entity } from "../Name.tsx";
import { AbilityMenu } from "../abilities/AbilityMenu.tsx";
import { RailButton } from "./RailButton.tsx";

export function OrgPanel() {
  const ui = useGameUi();
  const view = useView();
  const session = useSession();
  const flash = useFlash();
  const [open, setOpen] = useState(false);
  const [addLeader, setAddLeader] = useState(false);
  const [addOg, setAddOg] = useState(false);

  const channelId = ui.selected?.kind === "channel" ? ui.selected.id : null;
  const entry = orgOfChannel(view, channelId);
  if (!entry) return null;
  const [orgId, org] = entry;
  const accent = orgColorVar(org.name);
  const isAdmin = ui.viewer === "System";
  // The org's roster and abilities ride its own viewport. Frozen outranks membership below, since
  // membership reads the roster and the roster is one of the things that stopped updating — a view
  // that has lost the viewport can still be listed in an org it was thrown out of.
  const frozen = view.frozen(org.viewport);
  const isMember = isAdmin || org.members.has(ui.viewer);
  const members = orgMembers(view, orgId, org);
  const effectiveCount = members.filter((m) => m.effective).length;
  const candidates = [...view.players.keys()].filter((id) => !org.members.has(id));

  async function send(payload: Action, ok: string) {
    const reply = await session.submit_action({ actor: viewActor(ui.viewer), timestamp: Date.now(), payload });
    flash.reply(reply, ok);
  }
  function addMember(playerId: string) {
    send(
      { AddToOrg: { actor_id: slotKeyFromString(playerId), org_id: slotKeyFromString(orgId), leader: addLeader, og: addOg } },
      "Added.",
    );
  }
  function removeMember(playerId: string) {
    send({ RemoveFromOrg: { actor_id: slotKeyFromString(playerId), org_id: slotKeyFromString(orgId) } }, "Removed.");
  }
  function toggleOg(playerId: string, currentlyOg: boolean) {
    send({ SetOgStatus: { actor_id: slotKeyFromString(playerId), org_id: slotKeyFromString(orgId), og: !currentlyOg } }, "OG status updated.");
  }
  function toggleLeader(playerId: string, currentlyLeader: boolean) {
    send(
      { ChangeOrgLeader: { org_id: slotKeyFromString(orgId), new_leader: currentlyLeader ? null : slotKeyFromString(playerId) } },
      "Leader updated.",
    );
  }

  return (
    <>
      <RailButton active={open} onClick={() => setOpen(true)}>
        Organization
      </RailButton>

      <Modal
        open={open}
        onClose={() => setOpen(false)}
        width="32rem"
        title={
          <span className="flex items-center gap-2.5">
            <span className="h-3 w-3 shrink-0" style={{ backgroundColor: accent }} />
            <span style={{ color: accent }}>{orgDisplayName(org.name)}</span>
          </span>
        }
      >
        <div className="flex flex-col divide-y divide-edge">
          <div className="pb-4">
            {frozen ? (
              <p className="border-l-2 px-3 py-2 text-sm" style={tint("var(--color-event-alarm)")}>
                This organization no longer reaches you. Everything here is what you last saw.
              </p>
            ) : isMember ? (
              <AbilityMenu orgId={orgId} />
            ) : (
              <p className="border-l-2 border-edge bg-raised px-3 py-2 text-sm text-ink-dim">
                You are no longer in this organization. Everything here is what you last saw.
              </p>
            )}
          </div>

          <div className="flex flex-col gap-2 py-4">
            <div className="flex items-baseline justify-between gap-2">
              <span className="text-xs font-semibold uppercase tracking-widest text-ink-dim">Members</span>
              <span className="text-xs tabular-nums text-ink-dim">
                <span className="text-ink">{members.length}</span> total ·{" "}
                <span style={{ color: accent }}>{effectiveCount}</span> counted
              </span>
            </div>

            {members.length === 0 ? (
              <p className="py-1 text-sm text-ink-dim">No members.</p>
            ) : (
              <div className="flex flex-col border border-edge">
                {members.map((m) => (
                  <div key={m.id} className="flex flex-wrap items-center gap-2 border-b border-edge px-3 py-2 last:border-b-0">
                    <span className={`min-w-0 flex-1 truncate text-sm ${m.effective ? "text-ink" : "text-ink-dim"}`}>
                      {playerLabel(m.id, view.players)}
                    </span>
                    {!m.effective && (
                      <span
                        className="shrink-0 border border-edge px-1.5 py-0.5 text-xs font-medium uppercase tracking-wide text-ink-dim"
                        title="Not present, so not counted toward this org's ability member requirements. Still a full member."
                      >
                        not counted
                      </span>
                    )}
                    {m.leader && (
                      <span
                        className="shrink-0 border px-1.5 py-0.5 text-xs font-semibold uppercase tracking-wide"
                        style={{ color: accent, borderColor: accent }}
                        title="The org's leader. Only they and the host are told who this is."
                      >
                        Leader
                      </span>
                    )}
                    {m.og && (
                      <span
                        className="shrink-0 border px-1.5 py-0.5 text-xs font-semibold uppercase tracking-wide"
                        style={{ color: accent, borderColor: accent }}
                        title="An original member. Only they and the host know this."
                      >
                        OG
                      </span>
                    )}
                    {isAdmin && (
                      <span className="flex shrink-0 gap-1">
                        <Button variant="ghost" size="sm" title="Toggle leader" onClick={() => toggleLeader(m.id, m.leader)}>
                          leader
                        </Button>
                        <Button variant="ghost" size="sm" title="Toggle OG status" onClick={() => toggleOg(m.id, m.og)}>
                          og
                        </Button>
                        <Button variant="danger" size="sm" title="Remove from org" onClick={() => removeMember(m.id)}>
                          remove
                        </Button>
                      </span>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {isAdmin && (
            <div className="flex flex-col gap-2 pt-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <span className="text-xs font-semibold uppercase tracking-widest text-ink-dim">Add member</span>
                <div className="flex gap-3 text-xs text-ink">
                  <label className="flex items-center gap-1.5">
                    <input type="checkbox" checked={addLeader} onChange={(e) => setAddLeader(e.target.checked)} /> leader
                  </label>
                  <label className="flex items-center gap-1.5">
                    <input type="checkbox" checked={addOg} onChange={(e) => setAddOg(e.target.checked)} /> og
                  </label>
                </div>
              </div>

              {candidates.length === 0 ? (
                <p className="py-1 text-sm text-ink-dim">No one to add.</p>
              ) : (
                <div className="flex flex-col border border-edge">
                  {candidates.map((id) => (
                    <button
                      key={id}
                      type="button"
                      className="flex min-h-8 w-full items-center justify-between border-b border-edge px-3 py-2 text-sm text-ink last:border-b-0 hover:bg-raised"
                      onClick={() => addMember(id)}
                    >
                      <Entity of={{ kind: "player", id }} view={view} menu={false} />
                      <span className="shrink-0 text-xs uppercase tracking-wide text-ink-dim">add</span>
                    </button>
                  ))}
                </div>
              )}
              <FlashLine flash={flash} />
            </div>
          )}
        </div>
      </Modal>
    </>
  );
}
