// amane/amane-ui/game/channels/NotebookPass.tsx
// Pass (lend) a notebook to another player. Silent — it just dispatches LendNotebook; no logging or
// channel event. Mirrors the NotebookWrite modal, opened from the notebook channel.
import type { ActionRequest, NotebookKey } from "amane-client/bindings.ts";
import { slotKeyFromString } from "amane-client/bindings.ts";
import { viewActor } from "amane-client/queries/session.ts";
import { useState } from "react";
import { Button } from "../../kit/Button.tsx";
import { FlashLine, useFlash } from "../../kit/Flash.tsx";
import { Modal } from "../../kit/Modal.tsx";
import { useSession } from "../../hooks.ts";
import { useGameUi } from "../game_ui.ts";
import { PlayerSelect } from "../PlayerSelect.tsx";

export function NotebookPass({ open, onClose, notebookId }: { open: boolean; onClose: () => void; notebookId: NotebookKey }) {
  const session = useSession();
  const ui = useGameUi();
  const flash = useFlash();
  const [target, setTarget] = useState("");

  async function submit() {
    if (!target) {
      flash.error("Pick a player to pass to.");
      return;
    }
    const request: ActionRequest = {
      actor: viewActor(ui.viewer),
      timestamp: Date.now(),
      payload: { LendNotebook: { notebook_id: notebookId, target_id: slotKeyFromString(target) } },
    };
    const reply = await session.submit_action(request);
    if (flash.reply(reply, "Notebook passed.")) {
      setTarget("");
      onClose();
    }
  }

  return (
    <Modal open={open} onClose={onClose} title="Pass Notebook" footer={<Button onClick={submit}>Pass</Button>}>
      <div className="flex flex-col gap-3">
        <PlayerSelect value={target} onChange={setTarget} placeholder="Pass to" />
        <FlashLine flash={flash} />
      </div>
    </Modal>
  );
}

// amane/amane-core/ui/game/NotebookPass.svelte
<script lang="ts">
  // Pass (lend) a notebook to another player. Silent — it just dispatches LendNotebook; no
  // logging or channel event. Mirrors the NotebookWrite modal, opened from the notebook channel.
  import { execErrorText } from "../../game/helpers.svelte";
  import { getContext } from "svelte";
  import Dialog from "../kit/Dialog.svelte";
  import Button from "../kit/Button.svelte";
  import { SESSION_KEY, type SessionState } from "../../session.svelte.ts";
  import { UI_STATE_KEY } from "../../ui_state.svelte.ts";
  import { now } from "../../time.svelte.ts";
  import type { UiState } from "../../ui_state.svelte.ts";
  import type { ActionRequest, NotebookKey } from "../../bindings";
  import { slotKeyFromString } from "../../bindings";
  import { viewerToActor } from "../../types";
  import { Flash } from "../../flash.svelte.ts";
  import FlashDisplay from "../Flash.svelte";
  import PlayerSelect from "./abilities/PlayerSelect.svelte";

  interface Props {
    open: boolean;
    notebookId: NotebookKey;
  }
  let { open = $bindable(), notebookId }: Props = $props();

  const session = getContext<SessionState>(SESSION_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);

  let target = $state("");
  const flash = new Flash();

  async function submit() {
    if (!target) {
      flash.set_error("Pick a player to pass to.");
      return;
    }
    const request: ActionRequest = {
      actor: viewerToActor(ui.viewer),
      timestamp: now(),
      payload: {
        LendNotebook: {
          notebook_id: notebookId,
          target_id: slotKeyFromString(target),
        },
      },
    };
    const reply = await session.submit_action(request);
    if (!reply.ok) {
      flash.set_error(`Pass failed: ${execErrorText(reply.error)}`);
    } else {
      flash.set_success("Notebook passed.");
      target = "";
      open = false;
    }
  }
</script>

<Dialog bind:open title="Pass Notebook">
  <PlayerSelect bind:value={target} placeholder="Pass to" />

  <Button onclick={submit}>Pass</Button>
  <FlashDisplay {flash} />
</Dialog>
