// amane/amane-ui/game/side/Players.tsx
// The right rail's roster: who is in the open channel (or News) now, split by whether they can do
// anything there, and everyone else this view knows about.
import { slotKeyToString } from "amane-client/bindings.ts";
import { ownPerms } from "amane-client/game/perms.ts";
import type { MemberRow } from "amane-client/queries/players.ts";
import { channelRoster, otherPlayers, trueOwners } from "amane-client/queries/players.ts";
import { permsLabel, refFromDisplay } from "amane-client/text.ts";
import { Section } from "../../kit/Section.tsx";
import { useGameUi, useView } from "../game_ui.ts";
import { Entity } from "../Name.tsx";
import { Player } from "./Player.tsx";

export function Players() {
  const ui = useGameUi();
  const view = useView();
  const channelId =
    ui.selected?.kind === "news" ? view.news_channel : ui.selected?.kind === "channel" ? ui.selected.id : null;
  const { active, silent } = channelRoster(view, channelId);
  const others = otherPlayers(view, channelId);

  function memberRow(m: MemberRow) {
    const perms = ownPerms([m.profile]);
    const owners = trueOwners(view, channelId, m.profile);
    return (
      <div key={slotKeyToString(m.profile.profile_id)} className="flex flex-col">
        {m.playerId ? (
          <Player id={m.playerId} perms={perms} />
        ) : (
          // Nothing to contact or inspect. A role/org/anonymous display colours by its own entity
          // accent, exactly as that same display reads in a chat row.
          <div className="flex items-start justify-between gap-2 px-2 py-1.5 text-sm">
            <span className="min-w-0 break-words">
              <Entity of={refFromDisplay(m.profile.display, view.orgs)} view={view} menu={false} />
            </span>
            {permsLabel(perms) && <span className="shrink-0 text-xs text-ink-dim">{permsLabel(perms)}</span>}
          </div>
        )}
        {owners && owners.length > 0 && (
          // Admin only: the true holders of the name above, greyed and stacked so they read as an
          // annotation on that name rather than as player entries of their own.
          <div className="flex flex-col gap-0.5 pb-0.5 pl-3">
            {owners.map((name, i) => (
              <span key={i} className="text-xs text-ink-dim">
                {name}
              </span>
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <>
      <Section label="Channel Members">
        {!channelId ? (
          <p className="px-2 py-1 text-sm text-ink-dim">No channel selected</p>
        ) : active.length === 0 && silent.length === 0 ? (
          <p className="px-2 py-1 text-sm text-ink-dim">No members</p>
        ) : (
          <>
            {active.map(memberRow)}
            {silent.length > 0 && (
              <>
                <p className="px-2 pt-2 pb-0.5 text-xs font-medium uppercase tracking-wide text-ink-dim">
                  No permissions
                </p>
                {silent.map(memberRow)}
              </>
            )}
          </>
        )}
      </Section>
      <Section label="Other Players">
        {others.length === 0 ? (
          <p className="px-2 py-1 text-sm text-ink-dim">No other players</p>
        ) : (
          others.map((id) => <Player key={id} id={id} />)
        )}
      </Section>
    </>
  );
}

// amane/amane-core/ui/game/Players.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { GAME_STATE_KEY } from "../../game/state.svelte";
  import { actorDisplayColor, permsLabel, playerLabel } from "../../game/helpers.svelte";
  import { UI_STATE_KEY } from "../../ui_state.svelte.ts";
  import type { GameState } from "../../game/state.svelte";
  import type { UiState } from "../../ui_state.svelte.ts";
  import type { ActorDisplay, ChannelProfileView } from "../../bindings";
  import { slotKeyToString } from "../../bindings";
  import Player from "./Player.svelte";
  import Dropdown from "../kit/Dropdown.svelte";

  const game = getContext<GameState>(GAME_STATE_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);
  // The one view this component renders. Everything it can show is what this view was delivered.
  const view = $derived(game.view_of(ui.viewer));

  let channel_open = $state(true);
  let players_open = $state(true);

  // The channel whose members we show: the selected channel, or news's backing channel.
  const channel_id = $derived(
    ui.is_news ? view.news_channel_id : ui.selected_channel,
  );
  const channel_view = $derived(
    channel_id ? view.channel_views.get(channel_id) : undefined,
  );
  // Every name the room can see. A name it has not been told about is simply absent from the
  // roster, so there is nothing to filter out here.
  const members = $derived(channel_view?.roster ?? []);

  // Who actually holds each name, keyed by profile_id, as raw actor ids. Only the admin view is
  // ever told this, so for a player the map stays empty — a mask stays a mask and a Raw name is
  // taken at face value. Ids, not labels, because whether a Raw name is honest is an identity
  // comparison (see trueOwners).
  const owners_by_profile = $derived.by(() => {
    const map = new Map<string, string[]>();
    for (const entry of channel_view?.owners ?? []) {
      map.set(
        slotKeyToString(entry.profile_id),
        entry.owners.map((a) => slotKeyToString(a)),
      );
    }
    return map;
  });

  // The real holders to reveal beside a name (admin only), or null when the display already tells
  // the truth and nothing need be added. A mask — Mysterious or a role — names nobody, so its
  // holders are always worth showing. A Raw display claims one specific player; that is a lie worth
  // exposing unless that player is the name's sole holder, in which case the row is honest.
  function trueOwners(member: ChannelProfileView): string[] | null {
    const ids = owners_by_profile.get(slotKeyToString(member.profile_id));
    if (!ids || ids.length === 0) return null;
    const d = member.display;
    const claimed = typeof d !== "string" && "Raw" in d ? slotKeyToString(d.Raw) : null;
    if (claimed && ids.length === 1 && ids[0] === claimed) return null;
    return ids.map((id) => playerLabel(id, view.players));
  }

  // A member who holds nothing here is present but mute — no read, no send. They render in their
  // own group so a room full of names doesn't bury who can actually act in it.
  const active_members = $derived(members.filter((m) => m.perms !== 0));
  const silent_members = $derived(members.filter((m) => m.perms === 0));

  // Only Raw displays identify a specific player, so anonymous/role names stay in "other".
  const member_player_ids = $derived.by(() => {
    const ids = new Set<string>();
    for (const profile of members) {
      const d = profile.display;
      if (typeof d !== "string" && "Raw" in d) ids.add(slotKeyToString(d.Raw));
    }
    return ids;
  });
  const other_players = $derived(
    [...view.players.entries()].filter(([id]) => !member_player_ids.has(id)),
  );

  // Anonymous and role displays can't be contacted — you don't know who they are.
  function contact_target(display: ActorDisplay): string | null {
    return typeof display !== "string" && "Raw" in display
      ? slotKeyToString(display.Raw)
      : null;
  }
</script>

{#snippet ownerRows(owners: string[])}
  <!-- Admin only: the true holders of the name above. Greyed and stacked one per row so they read
       as an annotation on that name — never as player entries of their own. -->
  <div class="flex flex-col pl-3 pb-0.5">
    {#each owners as name, i (i)}
      <span class="text-xs text-neutral-500">{name}</span>
    {/each}
  </div>
{/snippet}

{#snippet memberRow(member: ChannelProfileView)}
  {@const pid = contact_target(member.display)}
  {@const owners = trueOwners(member)}
  <div class="flex flex-col">
    {#if pid}
      <Player id={pid} perms={member.perms} />
    {:else}
      <!-- nothing to contact or inspect. A role / org / anonymous display colours by its own entity
           accent, exactly as that same display reads in a chat row -- one colour source for the same
           thing in both surfaces. -->
      <div
        class="flex items-start justify-between gap-2 px-2 py-1.5 text-sm"
      >
        <span
          class="min-w-0 break-words font-medium"
          style="color: {actorDisplayColor(member.display, view)}"
        >
          {view.resolve_display(member.display)}
        </span>
        {#if permsLabel(member.perms)}
          <span class="shrink-0 text-xs text-neutral-600">
            {permsLabel(member.perms)}
          </span>
        {/if}
      </div>
    {/if}
    {#if owners && owners.length > 0}
      {@render ownerRows(owners)}
    {/if}
  </div>
{/snippet}

<div class="flex flex-col gap-1.5 pb-2">
  <Dropdown label="Channel Members" open={channel_open} onToggle={() => (channel_open = !channel_open)}>
      {#if !channel_id}
        <p class="px-2 py-1 text-xs text-neutral-600">No channel selected</p>
      {:else if members.length === 0}
        <p class="px-2 py-1 text-xs text-neutral-600">No members</p>
      {:else}
        {#each active_members as member (slotKeyToString(member.profile_id))}
          {@render memberRow(member)}
        {/each}

        {#if silent_members.length > 0}
          <p
            class="px-2 pt-2 pb-0.5 text-[0.6rem] font-medium uppercase tracking-wide text-neutral-600"
          >
            No permissions
          </p>
          {#each silent_members as member (slotKeyToString(member.profile_id))}
            {@render memberRow(member)}
          {/each}
        {/if}
      {/if}
  </Dropdown>

  <Dropdown label="Other Players" open={players_open} onToggle={() => (players_open = !players_open)}>
      {#each other_players as [id] (id)}
        <Player {id} />
      {/each}

      {#if other_players.length === 0}
        <p class="px-2 py-1 text-xs text-neutral-600">No other players</p>
      {/if}
  </Dropdown>
</div>
