// amane/amane-ui/game/side/Player.tsx
// One person row in the Players panel. The name is the trigger: clicking it opens the shared
// profile menu (contact / press conference / admin), so this row is just the name, its public
// statuses, and the channel read/send hint.
import { permsLabel, statusLabels } from "amane-client/text.ts";
import type { ChannelPerms } from "amane-client/game/types.ts";
import { statusAccent, tint } from "../../style.ts";
import { Entity } from "../Name.tsx";
import { useView } from "../game_ui.ts";

export function Player({ id, perms = null }: { id: string; perms?: ChannelPerms | null }) {
  const view = useView();
  const statuses = statusLabels(view.actor_statuses.get(id) ?? 0);
  const permsText = perms ? permsLabel(perms) : "";
  return (
    <div className="flex flex-wrap items-start justify-between gap-2 px-2 py-1.5 text-sm">
      <span className="flex min-w-0 flex-wrap items-center gap-1.5">
        <Entity of={{ kind: "player", id }} view={view} />
        {statuses.map((s) => (
          <span key={s} className="px-1 py-px text-xs uppercase tracking-wide" style={tint(statusAccent(s))}>
            {s}
          </span>
        ))}
      </span>
      {permsText && <span className="shrink-0 text-xs text-ink-dim">{permsText}</span>}
    </div>
  );
}

// amane/amane-core/ui/game/Player.svelte
<script lang="ts">
  // One person row in the Players panel. The name is the trigger: clicking it opens the shared
  // profile menu (contact / conference / admin), so this row is just the name, its public statuses,
  // and the channel read/send hint — no inline dropdown of its own anymore.
  import { permsLabel, statusLabels } from "../../game/helpers.svelte";
  import { getContext } from "svelte";
  import { GAME_STATE_KEY } from "../../game/state.svelte";
  import { UI_STATE_KEY } from "../../ui_state.svelte.ts";
  import type { GameState } from "../../game/state.svelte";
  import type { UiState } from "../../ui_state.svelte.ts";
  import Name from "./Name.svelte";

  interface Props {
    id: string;
    // read/send hint for channel members; omit (null) for non-members.
    perms?: number | null;
  }
  let { id, perms = null }: Props = $props();

  const game = getContext<GameState>(GAME_STATE_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);
  // The one view this component renders. Everything it can show is what this view was delivered.
  const view = $derived(game.view_of(ui.viewer));

  // The public condition of this player, as the world-data viewport last projected it.
  const statuses = $derived(statusLabels(view.actor_statuses.get(id) ?? 0));
</script>

<div class="flex items-start justify-between gap-2 px-2 py-1.5 text-sm">
  <span class="flex min-w-0 flex-wrap items-center gap-1.5">
    <Name {id} {view} />
    {#each statuses as s (s)}
      <span
        class="rounded bg-neutral-800 px-1 py-px text-[0.6rem] uppercase tracking-wide text-neutral-400"
      >
        {s}
      </span>
    {/each}
  </span>
  {#if perms !== null && permsLabel(perms)}
    <span class="shrink-0 text-xs text-neutral-600">{permsLabel(perms)}</span>
  {/if}
</div>
