// amane/amane-ui/game/abilities/AbilityMenu.tsx
// The generic abilities menu, in the bottom bar. With `orgId` it lists that org's shared abilities
// (dispatching UseOrgAbility instead of UseAbility) — the org panel reuses this component rather
// than duplicating a menu.
import { useState } from "react";
import { listAbilities, prettyAbility } from "amane-client/queries/abilities.ts";
import { abilityDescription, abilityWarning } from "amane-client/text.ts";
import { Button } from "../../kit/Button.tsx";
import { Modal } from "../../kit/Modal.tsx";
import { useView } from "../game_ui.ts";
import { AbilityCard } from "./AbilityCard.tsx";
import { ABILITY_UIS } from "./registry.ts";

export function AbilityMenu({ orgId }: { orgId?: string }) {
  const view = useView();
  const [open, setOpen] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null); // ability instance being configured

  const listed = listAbilities(view, orgId);
  const source = orgId ? view.orgs.get(orgId)?.abilities : view.abilities;
  const selectedAbility = selectedId ? source?.get(selectedId) : undefined;
  const SelectedForm = selectedAbility ? ABILITY_UIS[selectedAbility.name] : undefined;

  function close() {
    setOpen(false);
    setSelectedId(null);
  }

  const title =
    selectedId && SelectedForm && selectedAbility ? (
      <span className="flex items-center gap-2">
        <button type="button" className="text-ink-dim hover:text-ink" onClick={() => setSelectedId(null)} aria-label="Back to abilities">
          ←
        </button>
        {prettyAbility(selectedAbility.name)}
      </span>
    ) : orgId ? (
      "Org abilities"
    ) : (
      "Abilities"
    );

  return (
    <>
      <Button variant="ghost" size="sm" onClick={() => setOpen(true)}>
        {orgId ? "Org abilities" : "Abilities"}
      </Button>

      <Modal open={open} onClose={close} title={title}>
        {selectedId && SelectedForm && selectedAbility ? (
          <div className="flex flex-col gap-3">
            {abilityDescription(selectedAbility.name) && (
              <p className="text-sm text-ink-dim">{abilityDescription(selectedAbility.name)}</p>
            )}
            {abilityWarning(selectedAbility.name) && (
              <p className="text-sm text-danger-text">{abilityWarning(selectedAbility.name)}</p>
            )}
            <SelectedForm abilityId={selectedId} orgId={orgId} onDone={close} />
          </div>
        ) : (
          <div className="flex flex-col gap-2">
            {listed.map((ab) => (
              <AbilityCard
                key={ab.id}
                name={ab.name}
                successUsages={ab.successUsages}
                failureUsages={ab.failureUsages}
                resets={ab.resets}
                baseReset={ab.baseReset}
                unlimited={ab.unlimited}
                hasUi={ABILITY_UIS[ab.name] != null}
                requirements={ab.requirements}
                onUse={() => setSelectedId(ab.id)}
              />
            ))}
            {listed.length === 0 && <p className="py-2 text-sm text-ink-dim">No abilities.</p>}
          </div>
        )}
      </Modal>
    </>
  );
}

// amane/amane-core/ui/game/abilities/AbilityMenu.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { GAME_STATE_KEY } from "../../../game/state.svelte";
  import { UI_STATE_KEY } from "../../../ui_state.svelte.ts";
  import type { GameState } from "../../../game/state.svelte";
  import type { UiState } from "../../../ui_state.svelte.ts";
  import type { AbilityName, OrgAbility } from "../../../bindings";
  import { abilityDescription, abilityWarning } from "../../../game/helpers.svelte";
  import Dialog from "../../kit/Dialog.svelte";
  import Button from "../../kit/Button.svelte";
  import AbilityCard from "./AbilityCard.svelte";
  import {
    ABILITY_UIS,
    EXCLUDED_ABILITIES,
    prettyAbility,
  } from "./registry";

  // When `orgId` is set this menu drives that org's abilities (dispatching UseOrgAbility);
  // otherwise it drives the current viewer's personal abilities. Same UI either way, so
  // an org menu looks identical to the personal one — it's just a separate instance.
  let { orgId }: { orgId?: string } = $props();

  const game = getContext<GameState>(GAME_STATE_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);
  // The one view this component renders. Everything it can show is what this view was delivered.
  const view = $derived(game.view_of(ui.viewer));

  let open = $state(false);
  let selectedId = $state<string | null>(null); // ability instance being configured

  // The abilities this menu lists: an org's shared set, or the viewer's own.
  const source = $derived(
    orgId ? view.orgs.get(orgId)?.abilities : view.abilities,
  );

  // The abilities, minus ones surfaced through a dedicated widget.
  const listed = $derived.by(() => {
    const out: {
      id: string;
      name: AbilityName;
      successUsages: number;
      failureUsages: number;
      resets: number;
      baseReset: number;
      unlimited: boolean;
      requirements?: OrgAbility;
    }[] = [];
    for (const [id, av] of source ?? []) {
      if (EXCLUDED_ABILITIES.has(av.name)) continue;
      out.push({
        id,
        name: av.name,
        successUsages: av.success_usages_remaining,
        failureUsages: av.failure_usages_remaining,
        resets: av.iterations_to_reset,
        baseReset: av.base_reset,
        unlimited: av.unlimited,
        requirements: av.requirements,
      });
    }
    return out;
  });

  const selectedAbility = $derived(
    selectedId ? source?.get(selectedId) : undefined,
  );
  const SelectedUi = $derived(
    selectedAbility ? ABILITY_UIS[selectedAbility.name] : undefined,
  );

  function close() {
    open = false;
    selectedId = null;
  }
</script>

{#snippet drilledTitle()}
  <span class="flex items-center gap-2">
    <button
      class="text-ink-dim hover:text-ink"
      onclick={() => (selectedId = null)}
      aria-label="Back to abilities"
    >
      ←
    </button>
    {prettyAbility(selectedAbility!.name)}
  </span>
{/snippet}

<Button variant="ghost" size="sm" onclick={() => (open = true)}>
  {orgId ? "Org abilities" : "Abilities"}
</Button>

<Dialog
  bind:open
  onOpenChange={(o) => !o && (selectedId = null)}
  class="max-w-sm"
  title={selectedId && SelectedUi && selectedAbility
    ? undefined
    : orgId
      ? "Org abilities"
      : "Abilities"}
  header={selectedId && SelectedUi && selectedAbility ? drilledTitle : undefined}
>
  {#if selectedId && SelectedUi && selectedAbility}
    {@const desc = abilityDescription(selectedAbility.name)}
    {@const warn = abilityWarning(selectedAbility.name)}
    <div class="flex flex-col gap-3">
      {#if desc}
        <p class="text-sm text-ink-dim">{desc}</p>
      {/if}
      {#if warn}
        <p class="text-sm text-danger">{warn}</p>
      {/if}
      <SelectedUi abilityId={selectedId} {orgId} onDone={close} />
    </div>
  {:else}
    <div class="flex flex-col gap-2">
      {#each listed as ab (ab.id)}
        <AbilityCard
          name={ab.name}
          successUsages={ab.successUsages}
          failureUsages={ab.failureUsages}
          resets={ab.resets}
          baseReset={ab.baseReset}
          unlimited={ab.unlimited}
          hasUi={ABILITY_UIS[ab.name] != null}
          requirements={ab.requirements}
          onUse={() => (selectedId = ab.id)}
        />
      {/each}
      {#if listed.length === 0}
        <p class="py-2 text-sm text-ink-dim">No abilities.</p>
      {/if}
    </div>
  {/if}
</Dialog>
