// amane/amane-ui/game/abilities/PseudocideAbility.tsx
import { useState } from "react";
import type { ActorKey, OrgMemberView, Role } from "amane-client/bindings.ts";
import { slotKeyFromString } from "amane-client/bindings.ts";
import { abilityRequest } from "amane-client/queries/abilities.ts";
import { orgDisplayName, roleLabel } from "amane-client/text.ts";
import { useSession } from "../../hooks.ts";
import { Button } from "../../kit/Button.tsx";
import { FlashLine, useFlash } from "../../kit/Flash.tsx";
import { Input, Select } from "../../kit/Input.tsx";
import { useGameUi, useView } from "../game_ui.ts";
import { MentionInput } from "../mentions/MentionInput.tsx";
import { PlayerSelect } from "../PlayerSelect.tsx";
import { ROLES } from "amane-client/bindings.ts";
import type { AbilityUiProps } from "./registry.ts";

export function PseudocideAbility({ abilityId, orgId, onDone }: AbilityUiProps) {
  const session = useSession();
  const ui = useGameUi();
  const view = useView();

  const [target, setTarget] = useState("");
  const [trueName, setTrueName] = useState("");
  const [deathMessage, setDeathMessage] = useState("");
  const [role, setRole] = useState<Role>(ROLES[0]);
  const [notebookTransferred, setNotebookTransferred] = useState(false);
  const [abilityTransferred, setAbilityTransferred] = useState(false);
  // Fabricated affiliations to show on the fake death. Every org rides the data viewport, so any
  // of them can be named; each entry carries whatever leader/OG standing the faker wants seen.
  // Keyed by org actor key; absence means that org is not part of the lie.
  const [orgReveal, setOrgReveal] = useState<Record<string, OrgMemberView>>({});
  const flash = useFlash();

  function toggleOrg(key: string) {
    setOrgReveal((prev) => {
      if (prev[key]) {
        const next = { ...prev };
        delete next[key];
        return next;
      }
      return { ...prev, [key]: { leader: false, og: false } };
    });
  }

  function setOrgFlag(key: string, flag: "leader" | "og", value: boolean) {
    setOrgReveal((prev) => (prev[key] ? { ...prev, [key]: { ...prev[key], [flag]: value } } : prev));
  }

  async function fakeDeath() {
    if (!target) {
      flash.error("Pick whose death to fake.");
      return;
    }
    if (!trueName.trim()) {
      flash.error("A true name is required.");
      return;
    }
    const reply = await session.submit_action(
      abilityRequest(
        ui.viewer,
        abilityId,
        orgId,
        {
          Pseudocide: {
            target_id: slotKeyFromString(target),
            true_name: trueName,
            // Blank means "use the default death message" — send None, not an empty string.
            death_message: deathMessage.trim() ? deathMessage : null,
            role,
            orgs: Object.entries(orgReveal).map(
              ([key, v]) => [slotKeyFromString(key), v] as [ActorKey, OrgMemberView],
            ),
            notebook_transferred: notebookTransferred,
            ability_transferred: abilityTransferred,
          },
        },
        Date.now(),
      ),
    );
    if (flash.reply(reply)) onDone();
  }

  return (
    <div className="flex flex-col gap-3">
      <label className="flex flex-col gap-1 text-xs text-ink-dim">
        Target
        <PlayerSelect value={target} onChange={setTarget} placeholder="Whose death to fake" />
      </label>

      <label className="flex flex-col gap-1 text-xs text-ink-dim">
        True name revealed
        <Input value={trueName} onChange={(e) => setTrueName(e.target.value)} placeholder="True name" />
      </label>

      <div className="flex flex-col gap-1 text-xs text-ink-dim">
        <span>Death message</span>
        <MentionInput value={deathMessage} onChange={setDeathMessage} placeholder="Announced on death" />
      </div>

      <label className="flex flex-col gap-1 text-xs text-ink-dim">
        Role revealed
        <Select
          value={role}
          onChange={(e) => setRole(e.target.value as Role)}
          options={ROLES.map((r) => ({ value: r, label: roleLabel(r) }))}
        />
      </label>

      <div className="flex flex-col gap-1 text-xs text-ink-dim">
        Affiliations revealed
        <div className="flex flex-col gap-1 border border-edge bg-panel p-2">
          {[...view.orgs].map(([key, org]) => (
            <div key={key} className="flex items-center gap-2">
              <label className="flex flex-1 items-center gap-2 text-sm text-ink">
                <input type="checkbox" checked={!!orgReveal[key]} onChange={() => toggleOrg(key)} />
                {orgDisplayName(org.name)}
              </label>
              {orgReveal[key] && (
                <>
                  <label className="flex items-center gap-1 text-xs text-ink-dim">
                    <input
                      type="checkbox"
                      checked={orgReveal[key].leader}
                      onChange={(e) => setOrgFlag(key, "leader", e.target.checked)}
                    />
                    leader
                  </label>
                  <label className="flex items-center gap-1 text-xs text-ink-dim">
                    <input
                      type="checkbox"
                      checked={orgReveal[key].og}
                      onChange={(e) => setOrgFlag(key, "og", e.target.checked)}
                    />
                    og
                  </label>
                </>
              )}
            </div>
          ))}
          {view.orgs.size === 0 && <span className="text-ink-dim">No organizations to name.</span>}
        </div>
      </div>

      <label className="flex items-center gap-2 text-sm text-ink">
        <input
          type="checkbox"
          checked={notebookTransferred}
          onChange={(e) => setNotebookTransferred(e.target.checked)}
        />
        Notebook transferred
      </label>
      <label className="flex items-center gap-2 text-sm text-ink">
        <input
          type="checkbox"
          checked={abilityTransferred}
          onChange={(e) => setAbilityTransferred(e.target.checked)}
        />
        Abilities transferred
      </label>

      <Button variant="danger" onClick={fakeDeath}>
        Fake death
      </Button>
      <FlashLine flash={flash} />
    </div>
  );
}

// amane/amane-core/ui/game/abilities/PseudocideAbility.svelte
<script lang="ts">
  import { execErrorText, orgDisplayName } from "../../../game/helpers.svelte";
  import { getContext } from "svelte";
  import { GAME_STATE_KEY } from "../../../game/state.svelte";
  import { SESSION_KEY, type SessionState } from "../../../session.svelte.ts";
  import { UI_STATE_KEY } from "../../../ui_state.svelte.ts";
  import type { GameState } from "../../../game/state.svelte";
  import type { UiState } from "../../../ui_state.svelte.ts";
  import type { ActorKey, OrgMemberView, Role } from "../../../bindings";
  import { slotKeyFromString } from "../../../bindings";
  import { ROLES } from "../../../constants";
  import { Flash } from "../../../flash.svelte.ts";
  import FlashDisplay from "../../Flash.svelte";
  import PlayerSelect from "./PlayerSelect.svelte";
  import { useAbilityRequest, type AbilityUiProps } from "./registry";

  let { abilityId, onDone, orgId }: AbilityUiProps = $props();

  const game = getContext<GameState>(GAME_STATE_KEY);

  const session = getContext<SessionState>(SESSION_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);

  const view = $derived(game.view_of(ui.viewer));

  let target = $state("");
  let true_name = $state("");
  let death_message = $state("");
  let role = $state<Role>(ROLES[0]);
  let notebook_transferred = $state(false);
  let ability_transferred = $state(false);
  // Fabricated affiliations to show on the fake death. Every org rides the data viewport, so any of
  // them can be named; each entry carries whatever leader/OG standing the faker wants seen. Keyed by
  // org actor key; absence means that org is not part of the lie.
  let org_reveal = $state<Record<string, { leader: boolean; og: boolean }>>({});
  const flash = new Flash();

  function toggle_org(key: string) {
    if (org_reveal[key]) delete org_reveal[key];
    else org_reveal[key] = { leader: false, og: false };
  }

  async function fake_death() {
    if (!target) {
      flash.set_error("Pick whose death to fake.");
      return;
    }
    if (!true_name.trim()) {
      flash.set_error("A true name is required.");
      return;
    }
    const reply = await session.submit_action(
      useAbilityRequest(ui.viewer, abilityId, orgId, {
        Pseudocide: {
          target_id: slotKeyFromString(target),
          true_name,
          // Blank means "use the default death message" — send None, not an empty string.
          death_message: death_message.trim() ? death_message : null,
          role,
          orgs: Object.entries(org_reveal).map(
            ([key, v]) =>
              [slotKeyFromString(key), { leader: v.leader, og: v.og }] as [ActorKey, OrgMemberView],
          ),
          notebook_transferred,
          ability_transferred,
        },
      }),
    );
    if (!reply.ok) flash.set_error(execErrorText(reply.error));
    else onDone();
  }
</script>

<div class="flex flex-col gap-3">

  <label class="flex flex-col gap-1 text-xs text-neutral-500">
    Target
    <PlayerSelect bind:value={target} placeholder="Whose death to fake" />
  </label>

  <label class="flex flex-col gap-1 text-xs text-neutral-500">
    True name revealed
    <input
      bind:value={true_name}
      placeholder="True name"
      class="w-full rounded-md bg-neutral-800 px-2 py-2 text-sm text-neutral-200"
    />
  </label>

  <label class="flex flex-col gap-1 text-xs text-neutral-500">
    Death message
    <input
      bind:value={death_message}
      placeholder="Announced on death"
      class="w-full rounded-md bg-neutral-800 px-2 py-2 text-sm text-neutral-200"
    />
  </label>

  <label class="flex flex-col gap-1 text-xs text-neutral-500">
    Role revealed
    <select
      bind:value={role}
      class="w-full rounded-md bg-neutral-800 px-2 py-2 text-sm text-neutral-200"
    >
      {#each ROLES as r (r)}
        <option value={r}>{r}</option>
      {/each}
    </select>
  </label>

  <div class="flex flex-col gap-1 text-xs text-neutral-500">
    Affiliations revealed
    <div class="flex flex-col gap-1 rounded-md bg-neutral-800 p-2">
      {#each [...view.orgs] as [key, org] (key)}
        <div class="flex items-center gap-2">
          <label class="flex flex-1 items-center gap-2 text-sm text-neutral-300">
            <input
              type="checkbox"
              checked={!!org_reveal[key]}
              onchange={() => toggle_org(key)}
            />
            {orgDisplayName(org.name)}
          </label>
          {#if org_reveal[key]}
            <label class="flex items-center gap-1 text-xs text-neutral-400">
              <input type="checkbox" bind:checked={org_reveal[key].leader} /> leader
            </label>
            <label class="flex items-center gap-1 text-xs text-neutral-400">
              <input type="checkbox" bind:checked={org_reveal[key].og} /> og
            </label>
          {/if}
        </div>
      {:else}
        <span class="text-neutral-500">No organizations to name.</span>
      {/each}
    </div>
  </div>

  <label class="flex items-center gap-2 text-sm text-neutral-300">
    <input type="checkbox" bind:checked={notebook_transferred} />
    Notebook transferred
  </label>
  <label class="flex items-center gap-2 text-sm text-neutral-300">
    <input type="checkbox" bind:checked={ability_transferred} />
    Abilities transferred
  </label>

  <button
    class="rounded-md bg-neutral-100 px-3 py-2 text-sm font-medium text-neutral-900 hover:bg-white"
    onclick={fake_death}
  >
    Fake death
  </button>
  <FlashDisplay {flash} />
</div>
