// client/amane/ui/admin/AdminPanel.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { CLIENT_KEY, type ClientState } from "../../client.svelte.ts";
  import Button from "../kit/Button.svelte";
  import { Flash } from "../../flash.svelte.ts";
  import FlashDisplay from "../Flash.svelte";
  import { now } from "../../time.svelte.ts";
  import AddPlayers from "./AddPlayers.svelte";

  const client = getContext<ClientState>(CLIENT_KEY);
  const flash = new Flash();

  // Initialize Engine, Update and Offset lived here and are gone:
  //   - the server issues InitializeEngine itself on first boot, so an admin could only ever have
  //     sent a redundant second one;
  //   - Update was a manual Null to force catchup, which the null tick now drives on the clock;
  //   - Offset shifted the client's sense of "now" to time-travel an engine hosted in-process.
  //     yagami overwrites the timestamp on arrival, so against a server it did nothing at all.
</script>

<div class="flex items-center gap-2">
  <AddPlayers />

  <!-- Setup ends when the host says so, not when the world is created. Rejected once the game is
       running, so this is safe to leave in place rather than gate on a phase the client is not
       told. -->
  <Button
    onclick={async () => {
      const err = await client.dispatch({
        actor: "Admin",
        timestamp: now(),
        payload: { StartGame: {} },
      });
      if (err) flash.set_error(err);
      else flash.set_success("Day 1. Abilities and notebooks are live.");
    }}>Start Game</Button
  >

  <Button
    variant="danger"
    onclick={async () => {
      const err = await client.dispatch({
        actor: "Admin",
        timestamp: now(),
        payload: { Crash: {} },
      });
      // A crash comes back as the "engine has crashed" string (the runtime is respawned
      // and resaturated behind the scenes); surface it so the crash is actually visible.
      if (err) flash.set_error(err);
      else flash.set_success("No crash?");
    }}>Crash</Button
  >

  <FlashDisplay {flash} />
</div>

// amane/amane-ui/game/admin/AdminPanel.tsx
// The host's tools, as a row of buttons beside the rest of the bottom bar. Mounted only when this
// key administers the game (GameScreen gates on `administers(session)`).
import { useSession } from "../../hooks.ts";
import { Button } from "../../kit/Button.tsx";
import { FlashLine, useFlash } from "../../kit/Flash.tsx";
import { AddPlayers } from "./AddPlayers.tsx";
import { GoToTime } from "./GoToTime.tsx";
import { KeyManager } from "./KeyManager.tsx";
import { TimelineViewer } from "./TimelineViewer.tsx";

export function AdminPanel() {
  const session = useSession();
  const flash = useFlash();

  async function startGame() {
    // Rejected once the game is running, so this is safe to leave in place rather than gate on a
    // phase the client is not told.
    const reply = await session.submit_action({ actor: "Admin", timestamp: Date.now(), payload: { StartGame: {} } });
    flash.reply(reply, "Day 1. Abilities and notebooks are live.");
  }

  async function nextDay() {
    const reply = await session.submit_action({ actor: "Admin", timestamp: Date.now(), payload: { NextIteration: {} } });
    flash.reply(reply, "Day progressed.");
  }

  async function crash() {
    // A crash comes back as the "engine has crashed" string; the runtime is respawned and
    // resaturated behind the scenes, so surface it to make the crash visible at all.
    const reply = await session.submit_action({ actor: "Admin", timestamp: Date.now(), payload: { Crash: {} } });
    flash.reply(reply, "No crash?");
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      <AddPlayers />
      <KeyManager />
      <GoToTime flash={flash} />
      <TimelineViewer />
      <Button variant="ghost" size="sm" onClick={startGame}>
        Start Game
      </Button>
      <Button variant="ghost" size="sm" onClick={nextDay}>
        Next Day
      </Button>
      <Button variant="danger" size="sm" onClick={crash}>
        Crash
      </Button>
      <FlashLine flash={flash} />
    </div>
  );
}
