// amane/ui/game/abilities/AbilityMenu.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { GAME_STATE_KEY } from "../../../game_state.svelte.ts";
  import { UI_STATE_KEY } from "../../../ui_state.svelte.ts";
  import type { GameState } from "../../../game_state.svelte.ts";
  import type { UiState } from "../../../ui_state.svelte.ts";
  import type { AbilityName } from "../../../bindings";
  import * as Dialog from "$lib/components/ui/dialog";
  import AbilityCard from "./AbilityCard.svelte";
  import {
    ABILITY_UIS,
    EXCLUDED_ABILITIES,
    prettyAbility,
  } from "./registry";

  // When `orgId` is set this menu drives that org's abilities (dispatching UseOrgAbility);
  // otherwise it drives the current viewer's personal abilities. Same UI either way, so
  // an org menu looks identical to the personal one — it's just a separate instance.
  let { orgId }: { orgId?: string } = $props();

  const game = getContext<GameState>(GAME_STATE_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);

  let open = $state(false);
  let selectedId = $state<string | null>(null); // ability instance being configured

  // The abilities this menu lists: an org's shared set, or the viewer's own.
  const source = $derived(
    orgId ? game.orgs.get(orgId)?.abilities : game.views.get(ui.viewer)?.abilities,
  );

  // The abilities, minus ones surfaced through a dedicated widget.
  const listed = $derived.by(() => {
    const out: {
      id: string;
      name: AbilityName;
      successUsages: number;
      failureUsages: number;
      resets: number;
    }[] = [];
    for (const [id, av] of source ?? []) {
      if (EXCLUDED_ABILITIES.has(av.name)) continue;
      out.push({
        id,
        name: av.name,
        successUsages: av.success_usages_remaining,
        failureUsages: av.failure_usages_remaining,
        resets: av.iterations_to_reset,
      });
    }
    return out;
  });

  const selectedAbility = $derived(
    selectedId ? source?.get(selectedId) : undefined,
  );
  const SelectedUi = $derived(
    selectedAbility ? ABILITY_UIS[selectedAbility.name] : undefined,
  );

  function close() {
    open = false;
    selectedId = null;
  }
</script>

<Dialog.Root bind:open onOpenChange={(o) => !o && (selectedId = null)}>
  <Dialog.Trigger
    class="h-8 rounded-md border border-neutral-700 bg-neutral-900 px-3 text-sm text-neutral-200 hover:bg-neutral-800"
  >
    {orgId ? "Org abilities" : "Abilities"}
  </Dialog.Trigger>
  <Dialog.Content class="max-w-sm">
    {#if selectedId && SelectedUi && selectedAbility}
      <Dialog.Header>
        <Dialog.Title class="flex items-center gap-2">
          <button
            class="text-neutral-500 hover:text-neutral-200"
            onclick={() => (selectedId = null)}
            aria-label="Back to abilities"
          >
            ←
          </button>
          {prettyAbility(selectedAbility.name)}
        </Dialog.Title>
      </Dialog.Header>
      <SelectedUi abilityId={selectedId} {orgId} onDone={close} />
    {:else}
      <Dialog.Header>
        <Dialog.Title>{orgId ? "Org abilities" : "Abilities"}</Dialog.Title>
      </Dialog.Header>
      <div class="flex flex-col gap-2">
        {#each listed as ab (ab.id)}
          <AbilityCard
            name={ab.name}
            successUsages={ab.successUsages}
            failureUsages={ab.failureUsages}
            resets={ab.resets}
            hasUi={ABILITY_UIS[ab.name] != null}
            onUse={() => (selectedId = ab.id)}
          />
        {/each}
        {#if listed.length === 0}
          <p class="py-2 text-sm text-neutral-600">No abilities.</p>
        {/if}
      </div>
    {/if}
  </Dialog.Content>
</Dialog.Root>

// amane/amane-ui/game/abilities/AbilityMenu.tsx
// The generic abilities menu, in the bottom bar. With `orgId` it lists that org's shared abilities
// (dispatching UseOrgAbility instead of UseAbility) — the org panel reuses this component rather
// than duplicating a menu.
import { useState } from "react";
import { listAbilities, prettyAbility } from "amane-client/queries/abilities.ts";
import { abilityDescription, abilityWarning } from "amane-client/text.ts";
import { Button } from "../../kit/Button.tsx";
import { Modal } from "../../kit/Modal.tsx";
import { useView } from "../game_ui.ts";
import { AbilityCard } from "./AbilityCard.tsx";
import { ABILITY_UIS } from "./registry.ts";

export function AbilityMenu({ orgId }: { orgId?: string }) {
  const view = useView();
  const [open, setOpen] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null); // ability instance being configured

  const listed = listAbilities(view, orgId);
  const source = orgId ? view.orgs.get(orgId)?.abilities : view.abilities;
  const selectedAbility = selectedId ? source?.get(selectedId) : undefined;
  const SelectedForm = selectedAbility ? ABILITY_UIS[selectedAbility.name] : undefined;

  function close() {
    setOpen(false);
    setSelectedId(null);
  }

  const title =
    selectedId && SelectedForm && selectedAbility ? (
      <span className="flex items-center gap-2">
        <button type="button" className="text-ink-dim hover:text-ink" onClick={() => setSelectedId(null)} aria-label="Back to abilities">
          ←
        </button>
        {prettyAbility(selectedAbility.name)}
      </span>
    ) : orgId ? (
      "Org abilities"
    ) : (
      "Abilities"
    );

  return (
    <>
      <Button variant="ghost" size="sm" onClick={() => setOpen(true)}>
        {orgId ? "Org abilities" : "Abilities"}
      </Button>

      <Modal open={open} onClose={close} title={title}>
        {selectedId && SelectedForm && selectedAbility ? (
          <div className="flex flex-col gap-3">
            {abilityDescription(selectedAbility.name) && (
              <p className="text-sm text-ink-dim">{abilityDescription(selectedAbility.name)}</p>
            )}
            {abilityWarning(selectedAbility.name) && (
              <p className="text-sm text-danger-text">{abilityWarning(selectedAbility.name)}</p>
            )}
            <SelectedForm abilityId={selectedId} orgId={orgId} onDone={close} />
          </div>
        ) : (
          <div className="flex flex-col gap-2">
            {listed.map((ab) => (
              <AbilityCard
                key={ab.id}
                name={ab.name}
                successUsages={ab.successUsages}
                failureUsages={ab.failureUsages}
                resets={ab.resets}
                baseReset={ab.baseReset}
                unlimited={ab.unlimited}
                hasUi={ABILITY_UIS[ab.name] != null}
                requirements={ab.requirements}
                onUse={() => setSelectedId(ab.id)}
              />
            ))}
            {listed.length === 0 && <p className="py-2 text-sm text-ink-dim">No abilities.</p>}
          </div>
        )}
      </Modal>
    </>
  );
}
