// amane/amane-core/ui/game/abilities/FalseAnonymousContactAbility.svelte
<script lang="ts">
  import { execErrorText, roleLabel } from "../../../game/helpers.svelte";
  import { getContext } from "svelte";
  import { GAME_STATE_KEY } from "../../../game/state.svelte";
  import { SESSION_KEY, type SessionState } from "../../../session.svelte.ts";
  import { UI_STATE_KEY } from "../../../ui_state.svelte.ts";
  import type { GameState } from "../../../game/state.svelte";
  import type { UiState } from "../../../ui_state.svelte.ts";
  import { slotKeyFromString, type Role } from "../../../bindings";
  import { ROLES } from "../../../constants";
  import { Flash } from "../../../flash.svelte.ts";
  import FlashDisplay from "../../Flash.svelte";
  import PlayerSelect from "./PlayerSelect.svelte";
  import { useAbilityRequest, type AbilityUiProps } from "./registry";

  let { abilityId, onDone, orgId }: AbilityUiProps = $props();

  const game = getContext<GameState>(GAME_STATE_KEY);

  const session = getContext<SessionState>(SESSION_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);

  let target = $state("");
  let role = $state<Role>(ROLES[0]);
  const flash = new Flash();

  async function contact() {
    if (!target) {
      flash.set_error("Pick a target.");
      return;
    }
    const reply = await session.submit_action(
      useAbilityRequest(ui.viewer, abilityId, orgId, {
        FalseAnonymousContact: { target: slotKeyFromString(target), role },
      }),
    );
    if (!reply.ok) flash.set_error(execErrorText(reply.error));
    else onDone();
  }
</script>

<div class="flex flex-col gap-3">
  <PlayerSelect bind:value={target} placeholder="Target" />
  <label class="flex flex-col gap-1 text-xs text-neutral-500">
    Role to pose as
    <select
      bind:value={role}
      class="w-full rounded-md bg-neutral-800 px-2 py-2 text-sm text-neutral-200"
    >
      {#each ROLES as r (r)}
        <option value={r}>{roleLabel(r)}</option>
      {/each}
    </select>
  </label>
  <button
    class="rounded-md bg-purple-500 px-3 py-2 text-sm font-medium text-white hover:bg-purple-400"
    onclick={contact}
  >
    Contact as {roleLabel(role)}
  </button>
  <FlashDisplay {flash} />
</div>

// amane/amane-ui/game/abilities/FalseAnonymousContactAbility.tsx
import { useState } from "react";
import type { Role } from "amane-client/bindings.ts";
import { slotKeyFromString } from "amane-client/bindings.ts";
import { abilityRequest } from "amane-client/queries/abilities.ts";
import { roleLabel } from "amane-client/text.ts";
import { useSession } from "../../hooks.ts";
import { Button } from "../../kit/Button.tsx";
import { FlashLine, useFlash } from "../../kit/Flash.tsx";
import { Select } from "../../kit/Input.tsx";
import { useGameUi } from "../game_ui.ts";
import { PlayerSelect } from "../PlayerSelect.tsx";
import { ROLES } from "amane-client/bindings.ts";
import type { AbilityUiProps } from "./registry.ts";

export function FalseAnonymousContactAbility({ abilityId, orgId, onDone }: AbilityUiProps) {
  const session = useSession();
  const ui = useGameUi();
  const [target, setTarget] = useState("");
  const [role, setRole] = useState<Role>(ROLES[0]);
  const flash = useFlash();

  async function contact() {
    if (!target) {
      flash.error("Pick a target.");
      return;
    }
    const reply = await session.submit_action(
      abilityRequest(
        ui.viewer,
        abilityId,
        orgId,
        { FalseAnonymousContact: { target: slotKeyFromString(target), role } },
        Date.now(),
      ),
    );
    if (flash.reply(reply)) onDone();
  }

  return (
    <div className="flex flex-col gap-3">
      <PlayerSelect value={target} onChange={setTarget} placeholder="Target" />
      <label className="flex flex-col gap-1 text-xs text-ink-dim">
        Role to pose as
        <Select value={role} onChange={(e) => setRole(e.target.value as Role)} options={ROLES.map((r) => ({ value: r, label: roleLabel(r) }))} />
      </label>
      <Button onClick={contact}>Contact as {roleLabel(role)}</Button>
      <FlashLine flash={flash} />
    </div>
  );
}
