// amane/amane-core/ui/game/abilities/ShinigamiEyeDealAbility.svelte
<script lang="ts">
  import { execErrorText } from "../../../game/helpers.svelte";
  import { getContext } from "svelte";
  import { SESSION_KEY, type SessionState } from "../../../session.svelte.ts";
  import { UI_STATE_KEY } from "../../../ui_state.svelte.ts";
  import type { UiState } from "../../../ui_state.svelte.ts";
  import { Flash } from "../../../flash.svelte.ts";
  import FlashDisplay from "../../Flash.svelte";
  import { useAbilityRequest, type AbilityUiProps } from "./registry";

  let { abilityId, onDone, orgId }: AbilityUiProps = $props();

  const session = getContext<SessionState>(SESSION_KEY);
  const ui = getContext<UiState>(UI_STATE_KEY);

  const flash = new Flash();

  async function make_deal() {
    const reply = await session.submit_action(
      useAbilityRequest(ui.viewer, abilityId, orgId, { ShinigamiEyeDeal: {} }),
    );
    if (!reply.ok) flash.set_error(execErrorText(reply.error));
    else onDone();
  }
</script>

<div class="flex flex-col gap-3">
  <p class="text-sm text-ink-dim">
    Consumes this ability and grants you True Name Reveal. The world is told someone of your role has
    made the deal.
  </p>
  <button
    class="rounded-md bg-neutral-700 px-3 py-2 text-sm font-medium text-white hover:bg-neutral-600"
    onclick={make_deal}
  >
    Make the deal
  </button>
  <FlashDisplay {flash} />
</div>

// amane/amane-ui/game/abilities/ShinigamiEyeDealAbility.tsx
import { abilityRequest } from "amane-client/queries/abilities.ts";
import { useSession } from "../../hooks.ts";
import { Button } from "../../kit/Button.tsx";
import { FlashLine, useFlash } from "../../kit/Flash.tsx";
import { useGameUi } from "../game_ui.ts";
import type { AbilityUiProps } from "./registry.ts";

export function ShinigamiEyeDealAbility({ abilityId, orgId, onDone }: AbilityUiProps) {
  const session = useSession();
  const ui = useGameUi();
  const flash = useFlash();

  async function makeDeal() {
    const reply = await session.submit_action(
      abilityRequest(ui.viewer, abilityId, orgId, { ShinigamiEyeDeal: {} }, Date.now()),
    );
    if (flash.reply(reply)) onDone();
  }

  return (
    <div className="flex flex-col gap-3">
      <p className="text-sm text-ink-dim">
        Consumes this ability and grants you True Name Reveal. The world is told someone of your role has made
        the deal.
      </p>
      <Button variant="ghost" onClick={makeDeal}>
        Make the deal
      </Button>
      <FlashLine flash={flash} />
    </div>
  );
}
